### ISSUE TITLE
Not able to see Google Line Chart on ie8 or ie9

### ISSUE THREAD

**Issue by vip5sep** [angular-google-chart/angular-google-chart#105]
I am not able to see Google Line Chart individually just on ie8 or ie9. 
But when I run it on ie10, and change the compatibility to ie8 or ie9( using F12 and setting up browser mode on browser), it shows up. 

Please provide assistance, how I can run the chart app on ie8. I cannot update ie browser  version because of requirements. 
Also suggest some other chart control supporting AngularJS and accepting JSON Array for Chart( if any) , if Google chart is not supported on ie8 or ie9. 

Thanks for help in advance.

**Comment by vladmm** [comment]
@vip5sep Could you explain what was your issue and how did you solve it? I'm running into a similar problem, and your expertise might help. I don't have any logs or errors displayed. The chart is rendered. but without any data. 
In Firefox and Chrome the data is rendered properly on the chart.

Thanks!
