### ISSUE TITLE
Ability to create diffcharts

### ISSUE THREAD

**Issue by mhusari** [angular-google-chart/angular-google-chart#116]
Hi!

It looks like diffcharts are not available at the moment, it seems that all we need is ability to call computeDiff() on a chart object and change data after that. Is this correct and/or have I missed something?

Link to documentation on how to create DiffChart using "pure" google-charts:
https://google-developers.appspot.com/chart/interactive/docs/gallery/diffchart

**Comment by tiefenb** [comment]
Did someone try this?

**Comment by nbering** [comment]
Still haven't actually tried it, but you put it back on my radar. If I get time I'll see about making a demo or something. In the mean time, my theory is still sound. Most edge-case features are doable if you get access to the chart object.

**Comment by MikkaRibou** [comment]
Hi !

I am a recent angular user and I just started to use your library. It works like a charm except for diff charts. So I'm also interested in a demo because i don't understand the example put above, especially the "chartWrapper" variable (where it came from and how to use it for build a diff chart).

Thanks

**Comment by nbering** [comment]
Hi @MikkaRibou. Sorry, but while I think you might be able to work something out to use a diff chart, I simply don't have the time to create official support for it. I'm keeping some of these lesser-used features in mind going forward, but I have a relatively small amount of time for active development at the moment.

ChartWrapper is a wrapper class provided by the Chart API, and it is fundamental to how we support all types of charts without a lot of overly-complex code.

**Comment by eugenpodaru** [comment]
I know it's quite an old thread, but i recently needed support for diff charts and did a bit of research.

It is actually very easy to have diff charts with angular-google-chart. All that is needed is to add a new column with a role old-data to the data table.

Please see this example http://plnkr.co/edit/ei5qWMVT4vHj9AsxCyBV?p=preview

**Comment by nbering** [comment]
@eugenpodaru Oh wow! Nice find!

**Comment by ferchoman09** [comment]
@eugenpodaru Thanks ! Really good !
