### ISSUE TITLE
How about adding Timeline charts?

### ISSUE THREAD

**Issue by warren-pieterse** [angular-google-chart/angular-google-chart#124]
Is there any way to add Timeline charts to the directive?

**Comment by rocketegg** [comment]
Can you give an example of what the chartObject would look like for the Timeline?

**Comment by rocketegg** [comment]
Figured it out.  Including the <script> tags that load from google CDN was interfering with the chart rendering.  For reference, here's a working chart object:

      var chartObject = {};
      chartObject.type = "Timeline";
      chartObject.options = {};

      var dataTable = new google.visualization.DataTable();

      dataTable.addColumn({ type: 'string', id: 'President' });
      dataTable.addColumn({ type: 'date', id: 'Start' });
      dataTable.addColumn({ type: 'date', id: 'End' });
      dataTable.addRows([
        [ 'Washington', new Date(1789, 3, 29), new Date(1797, 2, 3) ],
        [ 'Adams',      new Date(1797, 2, 3),  new Date(1801, 2, 3) ],
        [ 'Jefferson',  new Date(1801, 2, 3),  new Date(1809, 2, 3) ]]);

      chartObject.data = dataTable;

      return chartObject;

**Comment by ikb42** [comment]
Note for those new to this, the above can also be done in object literal notation.
See https://google-developers.appspot.com/chart/interactive/docs/reference#DataTable
Something like this:
```
    $scope.chart = 
    {
        "type": "Timeline",
        "data": {
           "cols": [       
                { type: 'string', id: 'Position' }
                , { type: 'date', id: 'Start' }
                , { type: 'date', id: 'End' }                
          ]
          , "rows": [
                {
                  "c": [
                    { "v": "Washington" },
                    { "v": new Date(1789,3,29),
                      "f": "A long long time ago" },
                    { "v": new Date(1797,2,3),
                      "f": "A long long time ago" }
                  ]
                }, 
                {
                  "c": [
                    { "v": "Adams" },
                    { "v": new Date(1797,2,3) },
                    { "v": new Date(1801,2,3) }
                  ]
              }
          ]
        }
    };    
```
