### ISSUE TITLE
ReferenceError: google is not defined

### ISSUE THREAD

**Issue by sgarbesi** [angular-google-chart/angular-google-chart#129]
Getting the following error in console from v0.0.11 in Google Chrome:

```
ReferenceError: google is not defined
```

Which points to this line in the library:

```
								$scope.chartWrapper = new google.visualization.ChartWrapper(chartWrapperArgs), google.visualization.events.addListener($scope.chartWrapper, "ready", function() {
```

**Comment by Balrog30** [comment]
Closing this one, seems to have aged away. In summary, looks like it was probably incompatibility between AngularJS and RequireJS. Let me know if this is still an issue and I would happily re-open.
