### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by javiermarinros** [angular-google-chart/angular-google-chart#130]
It would be nice to add an option to animate the chart load using Google Chart API `animation` options and the method explained here: http://stackoverflow.com/a/14739666/528065

**Comment by RajuKanumuri** [comment]
Animation work with version '1.1', but not with version '1' we currently have in the ng-google-chart.js file.
Do you have any plans to update the latest API version or am I doing something wrong ?

In ng-google-chart.js File:
angular.module('googlechart', [])
        .value('googleChartApiConfig', {
            version: '1',
            optionalSettings: {
                packages: ['corechart']
            }
        })

In example.html File:
"animation": {
        "duration": 1000,
        "easing": 'in',
        "startup": true
 },

**Comment by bouil** [comment]
As "googleChartApiConfig" is a value, I think you can override it to the value that is suitable for you without changing the code source of the directive.

**Comment by RajuKanumuri** [comment]
We do bower install every time to get the latest.. being said that.. any updates I make to the ng-google-chart.js file would be temporary.

Is it the fact that animations won't work with the current version of  "angular-google-chart": "0.0.11" ??

**Comment by Balrog30** [comment]
What @bouil is saying is that you can do this in your angular app code without changing `ng-google-chart.js`. See `sample.js` in the root of the repository for an example. I also show this in more detail [here](http://nicholasbering.ca/angularjs/2015/02/10/agc-material-bar/) in the context of loading non-default packages.

**Comment by RajuKanumuri** [comment]
Thank you @Balrog30  and @bouil   for your quick response, I really appreciate your time. 
By adding the below code to my controller, I am able to bring animations to my charts.

.value('googleChartApiConfig', {
            version: '1.1',
            optionalSettings: {
                packages: ['corechart']
            }
