### ISSUE TITLE
Trying to use a graph outside angular view

### ISSUE THREAD

**Issue by JNKristiansen** [angular-google-chart/angular-google-chart#169]
Hi.

The graph directive works fine, and the graphs are showing in the view, but im trying to show 1 graph outside the view (regular javascript code and the chart API). Since the jsapi is loaded in in the factory, im just getting "google is not defined", and including the script fails everything else. Might be a stupid question, but cant wrap my mind around it.

**Comment by bouil** [comment]
You can try to load google chart api first, and loading your angular app and you regular charts only when google chart api is loaded.
See https://developers.google.com/chart/interactive/docs/quick_start and the function "setOnLoadCallback".
It has to be checked then how the directive behave if the google api is already loaded.

**Comment by JNKristiansen** [comment]
Brilliant. Thanks, that did the trick.
