### ISSUE TITLE
Generic handling of others event

### ISSUE THREAD

**Issue by bouil** [angular-google-chart/angular-google-chart#174]
Like asked in #125 and #173 , we shall be able to handle more kind of events.

One person have used the on-ready event to simply register a "select" listener using the plaingoogle api. That the easiest way to do it, and allow also to easily remove the listener using the google removeListener method. See #55 and #166 . The "$window.google" notation is however a bit clumsy and non intuitive (we could add the google object in the arguments of the onReady function https://github.com/bouil/angular-google-chart/blob/gh-pages/ng-google-chart.js#L192 ). That allows to register also one time listeners.

Another way to handle this may be using the "$attrs" variable of the link function, that should contains any attribute added to the directive. We then could have :

``` html
<div google-chart chart="chartObject" on-page="pageHandler(page)" style="height:600px; width:100%;"></div>
```

Searching the attrs for names starting with "on" and registering the event listener.

A third way to do this is to have a event object like this :

``` html
<div google-chart chart="myChart" event-handlers="chartHandlers"></div>
```

``` javascript
$scope.chartHandlers = {
  select: function (selectedItem){
    //some stuff
  },
  regionClick: function (region){
    //handle regionClick event for geoChart
  },
  rangechange: function (start, end){
    //Handle Range Change event for Annotation Charts
  }
};
```

.

**Comment by Balrog30** [comment]
So, it's pretty early stages, but I added a really quick doc page for the API I just added for the upcoming release.  See https://github.com/bouil/angular-google-chart/wiki/API-Documentation.  See the source code on the gh-pages branch for example usage.  I hope to be adding more helpful features in the future.

**Comment by HarelM** [comment]
The link above leads to an empty page...
Is it now possible to register for event on the directive itself without the need to know the google.visualization syntax?
I could not find it in the code...

**Comment by Balrog30** [comment]
I fixed the link.  That being said, what the link points to is documentation for the `GoogleChartController`, used by the `googleChart` directive in the version on gh-pages branch.  It's not entirely stable (there's some naming conflicts with ui-bootstrap).  I actively working on a version 0.1.0 release (hopefully for the beginning of October).  It doesn't "generically" handle all events, I just made a way to add directives for different event types that weren't handled before. If you let me know what event you want to handle, I could maybe make a custom build that will handle your needs now.

**Comment by HarelM** [comment]
I'm using the chart error wrapper so I.don't think it's urgent, but the event I register for are mouseover and mouseout. But they are related to specific chart type (I'm using area chart).

**Comment by Balrog30** [comment]
#215 added what you're looking for, I think.  Documentation in the pull request description. Note that in an area chart the `onmouseover` event only fires when you mouse over the actual data point, does not fire when hovering over the colored area of the chart.

**Comment by HarelM** [comment]
Just downloaded the beta release and replaced the namespaces, works like charm and does not require me to know what "charwrapper" is. Great! Thanks!
BTW, I would suggest to move the chart type to the html and split the data, options,view, formatters etc to be directives. This way the code in the cotroller will look cleaner:
Instead of:
```js
$scope.chart = {};
$scope.chart.type = "AreaChart";
$scope.chart.data = { some data };
```
You will have:
```html
<div google-chart chart="chart" agc-type="AreaChart" agc-data="data" ... />
```
Which on a brief look on the html you'd know which type of graph should be presented, and
```js
$scope.data = { some data };
```

but this is just my opinion (which I think is common in other chart directive I have tried out).
Keep up the good work!

**Comment by Balrog30** [comment]
@HarelM I agree.  It's part of my plan for full 0.1.0 release to include options for both the way it is done now, and separate attributes.  Both ways for easy migration, and because it may get rather verbose having all those attributes when you have a lot of behaviors plus ng-if, ng-class, etc.

**Comment by Balrog30** [comment]
Rather than go totally generic with event handler registration, I built and API for writing directives to handle events.  Some of them are already written. See #216 for the list of implemented events. I'll keep this open because applying event handlers from a collection is still a desirable feature, I think.

**Comment by nbering** [comment]
Changed my mind, trying to slim down the issues. Closing as we have a way to implement any wanted handlers in a consistent, but customizable way.
