### ISSUE TITLE
Build Process

### ISSUE THREAD

**Issue by Balrog30** [angular-google-chart/angular-google-chart#180]
I think the project has reached the point now where a build process would be beneficial.

I am personally inclined toward using [GruntJS](gruntjs.com).  I know people can have pretty strong feelings about build systems (as they do with text editors), so if any contributors feel strongly against Grunt, I would be willing to learn Gulp or some other system and use that.

## Suggested Build Tasks

* [x] Concat
* [x] Minify
* [x] jsHint
* [ ] Changelog
* [x] Test

### Concat

The main reason to add a build process for this project at this point is just to break up ng-google-chart.js into smaller files and then recombine them for release into one larger file. I use [grunt-contrib-concat](https://github.com/gruntjs/grunt-contrib-concat) for this in my own projects.

### Minify

I think the standard in the grunt world is [grunt-contrib-uglify](https://github.com/gruntjs/grunt-contrib-uglify).  I've never set up minification before, so I'm open to suggestions.

### jsHint

Pretty standard.  We've had a few pull requests just wanted to clean up jsHint warnings, so we might as well include it in the build process.

### Changelog

I've been looking at [git-changelog](https://github.com/rafinskipg/git-changelog) as a way to automatically generate a changelog as part of the release process.  For this to work we'd have to enforce a certain commit message requirements, but I think they're good practice anyway.  I've been starting to use this commit message style anyway just because it's very descriptive in a short message.  Setting up this build task is totally optional and very low priority.

### Test

Testing is very beneficial (especially in open source projects), as they provide a safety net when making changes, to to sure that existing behaviors and expectations do not break.  I have set up tests with Karma and Jasmine before, but I've only ever unit tested Controllers and Services before.  And I must admit that my own project's test coverage is abysmal at best.

I'm open to suggestions on this one, but writing integration tests with Protactor and sounds like a good fit, since our tight coupling with the Google Charts API makes true Unit Testing difficult.

Tests are a whole thing to themselves, but it makes sense to set up a build process before moving on to testing.

**Comment by Balrog30** [comment]
# A World of Pain

So, I was working on setting up some tests for angular-google-chart. You can see my progress so far at https://github.com/Balrog30/angular-google-chart/tree/unit-tests. I was under no illusion that this was going to be an easy road to walk down, but it should be very worthwhile. It was just a wee bit harder to get into than I was thinking it would be. Let's just say that I was working on this at my local 24-hour Starbucks as I often do, and was there from 8pm to 4am and only managed to complete some basic tests on two small components.

## The Root of the Problem

So, the main problem is trying to test the `GoogleChartController`. It just does way too much, and doesn't expose enough for testing. I managed to write a test that confirms that it registers a watcher. I managed to inject a mock version of the Google Charts API, and register a spy on `google.visualization.ChartWrapper`.

Then, I spend *hours* trying to get that spy to be called. Most issues on the internet seemed to be resolved by simple calls to `$rootScope.$apply()`, `$rootScope.$digest()`, or `$httpBackend.flush()` (a service we don't use). So I was kind of stumped and had to go home to bed.

The conclusion I could draw from this exercise is that the Controller just does **too much**. It's serving the following functions:

 * Directive Controller (linking the google chart to an element in the DOM)
 * Public API (a way a registering events to the google chart API)
 * $scope Manager (Registers and Handles Watch functions to update things when they are updated)
 * Draw Management (Calls the ChartWrappers Draw() function asynchronously)

This probably wouldn't all be quite so complicated if it didn't also manage the asynchronous state of the Google Visualization API.

So, I think I'm going to start by trying to break the Google Charts API related handling into a separate service, and have the GoogleChartsController be responsible for registering the watch on $scope (the Watch Handler itself can be part of the new Google Charts API Service), and exposing the "Public API" (not much choice here, Controllers are the only way to expose an API for one directive to another).

## Proposed Google Charts API Service Responsibilities

That means Draw Management, and creation and management of the `ChartWrapper`, event registration and handling, building of the `FormatManager` object - which handles the complexity of instantiating and applying Formatters - will all move to this new Service.

The goal of this change is to make the `GoogleChartController` and this new service easier to test independently of each other. With the current setup there is a very large portion of the module's logic that is contained in private and inaccessible functions.

## Changes to GoogleChartController

The "Public API" would also be expanded to include some of the responsibility that the controller already has. I was thinking that maybe it could have these new methods:

 * `getChartType()`
 * `setChartType(typeName)`
 * `getData()`
 * `setData(data)`
 * `getOptions()`
 * `setOptions(object)`
 * optionally `getOption(name)` and `setOption(name, value)`

This would eventually allow for something like this:

```HTML
<agc-chart agc-type=" 'LineChart' '" agc-data="chart.data" agc-options="chart.options"></agc-chart>
```

At the same time we could also do this:

```HTML
<agc-chart agc-object="chartObject"></agc-chart>
```

The change would allow users to break up the bits and pieces of the chart in their own code, so if the have essentially the same chart all over the place they could supply the options on `$rootScope` and the data on the more specific scope, just as an example.  Maybe that would be a bad pattern, but I think you probably get the idea.

## Timeline

I have no idea, but when this is done we'll definitely be on a completely different version. The changes I'm making are going to make this super duper flexible, but there's no way it can be compatible with the older version. I just hope I'm doing the right thing... the direction I'm taking this is trying to solve a lot of what people have been asking for, but there's a lot of fundamental changes that need to be made to get there.

I'm trying to build this so that it's easy to use for a one-off chart, but also expandable to the level of your creativity and technical skill if you have such a desire. But still keeping in mind that this is just a wrapper of the Google Charts API.

I think I should have something stable and with a suite of tests by October or November... but a lot can happen in a few months to slow me down. In the mean-time, I was thinking of checking out the version before I started on these major changes and pushing it out as a release.  There were a couple of things with `on-select` and some other small changes that were stable and could be made into an actual release now.

**Comment by bouil** [comment]
:+1: 

Can't find what to say.... that looks very good!

**Comment by Balrog30** [comment]
I changed my mind about the grunt change log plugin. Writing a change log manually makes for a much more useful result.
