### ISSUE TITLE
Unknown provider: googlechartProvider when using yeoman scaffolding 

### ISSUE THREAD

**Issue by melvey** [angular-google-chart/angular-google-chart#184]
This is a duplicate of issue #132 

When the googlechart module is included to an angular application created using yeoman the injector reports the following error
````
    Error: [$injector:unpr] Unknown provider: googlechartProvider <- googlechart
````

### To Replicate
I have replicated the issue on a new yeoman scaffold. Simply create a new angular application with yeoman (I excluded sass and bootstrap for my test but left in most angular modules)
````
$ yo angular
$ bower install angular-google-chart
````
Then add 'googlechart' to modules in app/scripts/app.js and app/scripts/controllers/main.js and run `grunt serve` to load the application. The error should appear in the javascript console.
I've also attempted downgrading angular and included modules to 1.2.28 as required by angular-google-charts but get the same error. 

### To Resolve
As per issue #132 replacing "googleJsapiUrl" with "googlechart" in ng-google-chart.js resolves the problem
line 21 replace
````
.provider('googleJsapiUrl', function () {
````
with
````
.provider('googlechart', function () {
````
line 37 replace
````
.factory('googleChartApiPromise', ['$rootScope', '$q', 'googleChartApiConfig', 'googleJsapiUrl', function ($rootScope, $q, apiConfig, googleJsapiUrl) {
````
with
````
.factory('googleChartApiPromise', ['$rootScope', '$q', 'googleChartApiConfig', 'googlechart', function ($rootScope, $q, apiConfig, googlechart) {
````
and on line 62 replace
````
script.src = googleJsapiUrl;
````
with
```` 
script.src = googlechart;
````

**Comment by Balrog30** [comment]
Where are you trying to inject `googlechart`?  That's a module name, not an injectable...

**Comment by melvey** [comment]
Sorry for the confusion. I'm not actually calling the injector myself, it is presumably getting injected as Angular attempts to load the module.

I am including it as I would any other module by declaring it as an argument to the controller. 
````
angular.module('angularChartsTestApp')
  .controller('MainCtrl', function ($scope, googlechart) {
    $scope.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
  });
````
This is on a yeoman scaffolded project and I believe the module is initially defined in app.js so I have also included it there
````
angular
  .module('angularChartsTestApp', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngRoute',
    'ngSanitize',
    'ngTouch',
    'googlechart'
  ])
````
This works successfully with the modified ng-google-chart.js described in my initial comment.

**Comment by Balrog30** [comment]
So... you don't normally inject a module into the controller like you are there.  There is no injectable item in angular-google-chart named `googlechart`, so there is no provider.  You can inject the googleChartApiPromise, which will [notfiy you when the api is available](http://nicholasbering.ca/angularjs/2015/04/02/google-charts-api-promise/), but there is no service, factory, controller, value, etc that matches the name of the module.

So, `angular.module('myApp', ['googlechart']);` is valid,
but `.controller('MainCtrl', function( googlechart){});` is not valid.

**Comment by melvey** [comment]
Ah thank you. I clearly misunderstood this one.

Thanks for your time
