### ISSUE TITLE
Chart responsive

### ISSUE THREAD

**Issue by luclanet** [angular-google-chart/angular-google-chart#187]
Is there any option to made the chart responsive?

Thanks

**Comment by Balrog30** [comment]
Sorry for the delay.  I tried to answer this right after you asked, but had connectivity issues.

#97 has some discussion about this.  If you look at the last comment, there's a tiny bit of code fore example usage.

Keep in mind also, you can just use normal responsive methods with CSS, you just need to make sure that your chart container has both width and height set.  There's nothing built into google charts to make them responsive.
