### ISSUE TITLE
Sample charts not loading

### ISSUE THREAD

**Issue by codenameEli** [angular-google-chart/angular-google-chart#189]
The only page that has working demos is the "Multi Charts sample". Think it is because the URL to Bootstrap is broken.
![image](https://cloud.githubusercontent.com/assets/4925333/8175535/d6467a5a-13b9-11e5-90a3-ec6780fe6256.png)

**Comment by Balrog30** [comment]
Same as #188.  Looking into this.

**Comment by Balrog30** [comment]
Should be fixed.
