### ISSUE TITLE
Geochart: colorAxis doesn't show gradient

### ISSUE THREAD

**Issue by pmMarianP** [angular-google-chart/angular-google-chart#192]
Hi,
I found just a small issue.

reported here:
http://stackoverflow.com/questions/29328092/google-charts-geochart-coloraxis-doesnt-show-gradient
workaround here:
https://github.com/google/google-visualization-issues/issues/598

I am able to do it by myself. But maybe for other users it could be annoying. So for them it could be nice, if your module do it automatically.

**Comment by Balrog30** [comment]
I need some time to look at this.  The underlying issue has some very complex workarounds that will probably take me a bit to understand well enough to determine if they would have a negative impact on users who don't know it's there.

I don't have a timeline on writing a feature if we do add this, but I will assess the risk vs benefits soon.

**Comment by Balrog30** [comment]
At first glance I thought this was an issue that Google wasn't going to touch on their end, but now I see the issue you linked was closed on May 9, and it was just 6 days ago that @g3852477 commented about this issue.  I would suggest you approach the Google Charts team about this first, then we can decide if something should be done.

If they really aren't going to fix this, then maybe we can get some kind of work around going, but the hack they published in their issues repo is jQuery proper, not the jqLite included with Angular, and angular-google-chart currently has no dependency on jQuery.

The best I can suggest is perhaps some kind of console hint linking to this issue if we detect the presence of the conditions leading to this bug, and then let the developer decide whether to remove the base tag, add jQuery to their project, or whatever they want to do.

I'm not going to close this issue, yet, but I'm marking it "won't fix" until I see sign that google isn't going to fix the problem.  I've also subscribed to the GitHub issue you linked, so I will know if there is some response there.

**Comment by Balrog30** [comment]
@g3852477 opened google/google-visualization-issues#2000 dedicated to this lingering issue, and @dlaliberte has stated that this problem will be fixed in next release.  I'm not sure when the next release will be, but it's probably faster than we've been releasing.  Closing this issue, but I'll still be watching the google-visualization counterpart for updates.

**Comment by miguelalche** [comment]
Hey @nbering in the last issue you referenced the last comment seems to have solved this problem by using version 43 if I understand correctly. 
Could angular-google-chart be updated to reference that version of google charts?

**Comment by nbering** [comment]
@miguelalche Frozen version support is on the roadmap for the next version, but I haven't had much time for development on this project lately. It'll be at least a couple of weeks before I can start implementation on that.

**Comment by Tiagojdferreira** [comment]
@nbering any news on the support for using fronzen versions ? I have the same problem and I can't seem to be able to fix it :/

**Comment by nbering** [comment]
@Tiagojdferreira There's a pull request in a progress. I'm just waiting for some free time to evaluate and merge. Feel free to check it out and make comments on how you feel about the implementation. #270
