### ISSUE TITLE
Dual Vertical Axes

### ISSUE THREAD

**Issue by coscallis** [angular-google-chart/angular-google-chart#193]
"Raw" google chart allow for dual vAxis using options that look something like:
_________________________________________________________________________
var options = {
                    title: "Monthly Sales Activity-Last 12 months",
                    "vAxis": {
                        0: {
                            "title": "Units (x 1000)",
                            "minValue": 0,
                            "gridlines": {
                                "count": 5
                            }
                        },
                        1: {
                            "title": "Dollars",
                            "minValue": 500000,
                            "maxValue": 1000000,
                            "gridlines":{
                            "count": 5
                            }
                        }
                    },
                    hAxis: {
                        title: "Month"
                    },
                    seriesType: "bars",
                    series: {
                        0: { "targetAxis": 0 },
                        1: { "targetAxis": 1, "type": "line" }
                    }
                };
_______________________________________________________________
I have tried several variations on the syntax for declaring the options...
if I omit the 2nd vAxes all works 'as expected'...what ever I try to get the 2nd vAxes display causes both vAxes to not display. (google charts then seems to apply it's own function to set the primary vAxis. ...)

If there is currently a correct way to do this I would like to know it. 
If not, I would like to request this be added as a feature.

**Comment by Balrog30** [comment]
What type of chart is this for?

**Comment by coscallis** [comment]
in this case a comboChart (bar & line): 
In this example from JSFiddle you see a line chart w/dual vAxes.... http://jsfiddle.net/e1b3ggsb/ 
Then I Forked it to show a combo with dual vAxes (my goal)... http://jsfiddle.net/erwmb4nL/
some of the examples I used to come up with what I tried include...
http://stackoverflow.com/a/9650352/681009
http://www.marinamele.com/2014/04/google-charts-double-axes.html
https://developers.google.com/chart/interactive/docs/gallery/linechart (see "Duel Y Charts" down the page)

I have tried a variety of variations of the options shown above, but can not get it right...

**Comment by Balrog30** [comment]
Ah.  I see your error now.  You have `vAxis` instead of `vAxes`.  Can't believe I didn't catch that sooner.  Give it a try.

**Comment by coscallis** [comment]
Okay...well that wins the 'well duh' prize for the day...color me red with embarrassment. Thanks for your help.

**Comment by Balrog30** [comment]
No problem.  I was trying to figure out myself what was wrong.  I use this feature too, and the only thing I could think of at first was unsupported chart type.
