### ISSUE TITLE
Ability to dynamically set chart language

### ISSUE THREAD

**Issue by stefannorman** [angular-google-chart/angular-google-chart#194]
To initially set the language to Swedish (sv) of Google Chart I have this working piece of code in my app.js:
```javascript
app.constant('googleChartApiConfig', {
    version: '1',
    optionalSettings: {
      packages: ['corechart'],
      language: 'sv'
    }
  });
```
However, I am looking for a way to set the language dynamically without reloading the page. 
That might be a limitation with `google.load` though. I added these two rows to the factory:
```javascript
window.google.load('visualization', apiConfig.version, settings);

// trying to get Swedish after initial google.load call.
settings.language = 'sv';
window.google.load('visualization', apiConfig.version, settings);
```

But there is still only one network request to https://www.google.com/uds/?file=visualization&v=1&hl=en&packages=corechart&async=2 
I e, no second call. 

From the Google Dev Docs
> Note that the loader keeps track of what has already been loaded, so if you try loading the same visualization package multiple times it won't bother reloading it each time. 

I guess that the second call is not made because only the language setting changed.

Is there any workaround for this?

**Comment by Balrog30** [comment]
As far as I know, there is not.  I believe it is explicitly stated in Google's documentation somewhere that once you request the packages with one language setting, it will not request another without a reload.
