### ISSUE TITLE
Question for the next new version.

### ISSUE THREAD

**Issue by Piicksarn** [angular-google-chart/angular-google-chart#205]
excuse me , i would like to know when the next new version will be released？
and whether included with  **ng-google-chart.js.map** and **ng-google-chart.min**?

thank you :)
Piicksarn

**Comment by Balrog30** [comment]
I don't have a timeline on next official release at this time.  I'm pretty busy at work and want to finish some documentation and make absolute certain there are no bugs before I make the work in progress official.

I think it would probably be best to remove source mapping from the official released version of the files as it is only a feature meant to help debug at development time.

**Comment by Balrog30** [comment]
Wow.  I literally just noticed the reference to the pull request on cdnjs... that's good to know. Is there anything I need to know about maintaining that listing? I had looked at it briefly before this issue was posted, but never took the time to learn how it worked.
