### ISSUE TITLE
Timeline Charts: Custom HTML Tool Tips

### ISSUE THREAD

**Issue by agentVargas2012R** [angular-google-chart/angular-google-chart#206]
Hello,

I'm attempting to add tooltips to Google Chart Timelines, I am able to get the timeline to appear and the content to place properly, however, I haven't figured out exactly how to place a customizable html tooltip on the graph. 

I'm using this as my reference: https://developers.google.com/chart/interactive/docs/gallery/timeline particularly, "Customizing tooltips" as my basis for this. 

```javascript
return {
          "cssStyle" : "height:300px;width:100%;",
          "type": "Timeline",
          "data": {
             "cols": [       
                  { type: 'string', id: 'Program' }, 
                  { type: 'string', id: 'dummy bar label' },
                  { type: "string", id: "", "role": "tooltip",  "p" : { "role" : "tooltip" ,'html': true} }, 
                  { type: 'date', id: 'Start' }, 
                  { type: 'date', id: 'End' },                          
            ]
            , "rows": [
                  {
                    "c": [
                      { "v": "HRPP" },
                      { "v": "Points"},
                      { "v": "<strong>10234</strong>" },
                      { "v": new Date(2013,2,3) },
                      { "v": new Date(2015,5,3) },
                    ]
                  },
                  {
                    "c": [
                      { "v": "CUP" },
                      { "v": "Transferable"},
                      { "v": "10234 Transferable Pts" },
                      { "v": new Date(2013,2,3) },
                      { "v": new Date(2015,5,3) }
                      
                    ]
                  },  
                  {
                    "c": [
                      { "v": "CUP" },
                      { "v": "Points"},
                      { "v": "14234 Pts" },
                      { "v": new Date(2015,5,4) },
                      { "v": new Date(2017,8,3) }
                      
                    ]
                  }                                  
            ]
          }, 
          "options" : {
            timeline: {
                //singleColor: '#00f',
                colorByRowLabel: false,
                groupByRowLabel: true,
                rowLabelStyle: {fontName: 'Helvetica', fontSize: 18, color: '#442' },
                barLabelStyle: { fontName: 'Garamond', fontSize: 14 }
            },
            backgroundColor: '#ffffff',
            tooltip: {
              isHtml: true
            }
          }
      };   

Is this feature supported for timelines?

**Comment by Balrog30** [comment]
There's nothing in Angular-Google-Chart to prevent this from working.  If there's a problem on Google's end, I have no idea.  I have limited time to help out, if you could set up a [plunker](http://plnkr.co) or jsfiddle or something I'd be happy to help you debug it.  I just don't have time to do all the setup for troubleshooting right now.

**Comment by agentVargas2012R** [comment]
@Balrog30  - No problem. I totally understand, I have created a JSBIN here:
https://jsbin.com/yanale/edit?js,output

Any insight would be awesome. 

Best!

**Comment by Balrog30** [comment]
@agentVargas2012R - Thanks, your demo make me smile. If only I had that much cash, maybe I wouldn't have to keep so busy. :smile:

Ok, to the solution!

# Solution

See my fixed [jsBin](https://jsbin.com/hucagu/1/edit?js,output) for the interactive version.  Basically, after quite a bit of poking around trying to get the demo to work, I noticed that if I set up the data with null values as the [Google Demo](https://developers.google.com/chart/interactive/docs/gallery/timeline#customizing-tooltips) had, it produced an error.  This definitely did not match the behaviour of the documentation page.

That led me to the solution.  The version of the charts API used in that demo was `1.1`.  It is the only demo on that page that uses `1.1`.  Therefore, you stumbled upon a feature that is version-specific.  I fixed the bin by overriding the angular-google-chart options to load the correct version.

```JavaScript
app.value('googleChartApiConfig', {
            version: '1.1',
            optionalSettings: {
                packages: ['timeline'],
                language: 'en'
            }
    });
```

By the way, I like how you wrote a service that returns a chartObject.  That is some good decoupling.  I've never seen it done this way, and hadn't even thought to do it myself.  I usually return the data from a service and assemble the chart object in the controller.

**Comment by agentVargas2012R** [comment]
@Balrog30  - Dude...you rock! Thanks very much for looking into this! Also - please feel free to use my sample on your readme page if you like the implementation style. You guys do great work and are solid on assistance. I would like to contribute in any way I can to show my support. 

Best!
