### ISSUE TITLE
Calendar Chart type

### ISSUE THREAD

**Issue by piyushchauhan2011** [angular-google-chart/angular-google-chart#209]
Do we support `CalendarChart` type ?

**Comment by Balrog30** [comment]
Yes, all chart types are supported.

**Comment by piyushchauhan2011** [comment]
![screen shot 2015-08-17 at 11 42 52 pm](https://cloud.githubusercontent.com/assets/693487/9306139/ca02b108-4539-11e5-87d9-c47443f98272.png)

I think maybe `type` is not `CalendarChart` ?

**Comment by piyushchauhan2011** [comment]
So I realized that we have to load the `calendar` visualization. How we can use `googleChartApiConfig` object to pass the `calendar` visualization just like this one:

`google.load("visualization", "1.1", {packages:["calendar"]});`

**Comment by piyushchauhan2011** [comment]
Right now I used `googleChartApiConfig` like this, I don't is this a better way to use.
Inject into controller and do following:

```javascript
  googleChartApiConfig.optionalSettings = { packages: ['corechart', 'calendar'] };
  googleChartApiConfig.version = '1.1';
```

**Comment by Balrog30** [comment]
Type names match the name of the object constructor in the charts library. Calendar is `google.visualization.Calendar` so the type you are looking for is `Calendar`.

**Comment by Balrog30** [comment]
You can find all of the chart names and the options they accept at https://developer.google.com/chart
