### ISSUE TITLE
Project/Organization Logo

### ISSUE THREAD

**Issue by Balrog30** [angular-google-chart/angular-google-chart#211]
![agc-logo](https://cloud.githubusercontent.com/assets/4421371/9538949/5e8d9316-4d18-11e5-942e-63dbc4d64b3f.png)
I was just playing around at making a logo. I'm not a designer and was just using Inkscape to make this. This is pretty rough. I picked the colour pretty much at random, and didn't even really try to make the bars even widths. What do you think @bouil?

**Comment by bouil** [comment]
I like the idea and the reference to the shape of the AngularJS logo. I didn't like so much the green/blue background color though.

But I'm very bad at design so I could not do anything better ;-)

**Comment by Balrog30** [comment]
Here's some colour options some across the spectrum. I can tweak some of the bolder colours to ligten them up and make it easier to see the chart graphic. I'm kind of leaning toward the blue as-is myself.
![agc-logo-1](https://cloud.githubusercontent.com/assets/4421371/9548320/f05607ba-4d6d-11e5-9f1c-01d802d6ec97.png)
![agc-logo-2](https://cloud.githubusercontent.com/assets/4421371/9548323/f4a060fe-4d6d-11e5-983e-31b87b2ddc91.png)
![agc-logo-3](https://cloud.githubusercontent.com/assets/4421371/9548328/fa12e494-4d6d-11e5-8694-31d0eea27f86.png)
![agc-logo-4](https://cloud.githubusercontent.com/assets/4421371/9548331/feacba0c-4d6d-11e5-8ce7-6eb8f0393ffd.png)

**Comment by bouil** [comment]
In order of preference, I would say 2, 4, 3 and then 1.

**Comment by Balrog30** [comment]
That was a speedy response. :+1:
I agree. I like 2 best. Next I'll play with the charts. I've got a few ideas to try.

**Comment by Balrog30** [comment]
Personally, I'm a little bit torn between keeping it simple with 5, and the white grid lines with 7. Willing to try anything.
![agc-logo-5](https://cloud.githubusercontent.com/assets/4421371/9559873/de379f1e-4dca-11e5-802f-f13d4a527201.png)
![agc-logo-6](https://cloud.githubusercontent.com/assets/4421371/9559874/e0c22f7e-4dca-11e5-9866-5957d1283bce.png)
![agc-logo-7](https://cloud.githubusercontent.com/assets/4421371/9559875/e3f84c1e-4dca-11e5-8f46-8e953eef106f.png)
![agc-logo-8](https://cloud.githubusercontent.com/assets/4421371/9559876/e75f8bb0-4dca-11e5-9163-aeca8970a9c2.png)

**Comment by bouil** [comment]
I prefer it more simple without the lines, so 5 for me.

**Comment by Balrog30** [comment]
5 it is. Unless there are any suggestion, I'll commit the artwork to gh-pages the next time I'm on my Mac, with the original SVG and a few sizes of PNG for convenience.

**Comment by Balrog30** [comment]
Merged in PR #214.
