### ISSUE TITLE
Cant find event listener for select

### ISSUE THREAD

**Issue by mauleshmevada** [angular-google-chart/angular-google-chart#212]
I want to integrate geo map chart and I am trying to integreate it with my project but I ddidnt find event for select.

**Comment by Balrog30** [comment]
One sentence doesn't give me much to go on.  What do you mean by "didn't find event"? As in, you couldn't find documentation?

**Comment by Balrog30** [comment]
If you could please give me a better idea of what you require help with, I can certainly give you assistance. I am closing the issue for the moment as I can't help with the detail given, but I will certainly re-open the issue if you get back to me.  Thank you.
