### ISSUE TITLE
support for timeline

### ISSUE THREAD

**Issue by joaovicente** [angular-google-chart/angular-google-chart#227]
I have not seen an example demonstrating timelines (https://developers.google.com/chart/interactive/docs/gallery/timeline). Is is supported? If so, could you provide an example?

**Comment by Balrog30** [comment]
See #124. Adding more examples to the docs site is on my todo list, but I unfortunately do not have time at the moment to add content.

**Comment by joaovicente** [comment]
Thanks for referencing a similar question and for getting back in such short time frame. I will be creating a jsfiddle soon and will post in this thread as it may help ohers.
