### ISSUE TITLE
Add minify file to bower package.

### ISSUE THREAD

**Issue by mapeveri** [angular-google-chart/angular-google-chart#230]
Now when installed the package via bower, not contains the file ng-google-chart.min.js. Can you add?.

Thanks!

**Comment by Balrog30** [comment]
Minification was not part of our build process before the past "official" release. There is a minified file if you use the beta releases - 0.1.0-beta.x Nothing has changed in beta for a while and no one has complained, so I may just flip them into a full release soon. I was just giving it some time for people to report bugs.

**Comment by mapeveri** [comment]
@Balrog30 perfect, thanks :)
