### ISSUE TITLE
Implementing gantt charts?

### ISSUE THREAD

**Issue by brahalla** [angular-google-chart/angular-google-chart#231]
Is there any plan to implement the new gantt chart type Google has introduced?

https://developers.google.com/chart/interactive/docs/gallery/ganttchart

**Comment by Balrog30** [comment]
This project does not implement any charts, it just wraps the API to expose it in a more angular-friendly way. We're using ChartWrapper as an interface. To use Gantt charts with Angular Google Chart, set `type:GanttChart` on your chart object, and structure your data as instructed by the Google documentation. You may also need to import the gantt package. The documentation on how to configure the charts API can be found here: http://angular-google-chart.github.io/angular-google-chart/docs/0.0.11/values/googleChartApiConfig/

**Comment by brahalla** [comment]
Thanks!

**Comment by outis10** [comment]
Hi, I get a invalid vizualization type

 I put the type as you say  in mi controller

`$scope.myChartObject.type = "GanttChart";`

then in the apiconfig

`.value('googleChartApiConfig', {
    version: '1.1',
    optionalSettings: {
        packages: ['corechart', 'gantt'],
        language: 'es'
    }`

the data is set here

        $scope.myChartObject.data = {
            "cols": [
                {id: 'Task ID', type: 'string'},
                {id: 'Task Name', type: 'string'},
                {id: 'Start Date', type: 'date'},
                {id: 'End Date', type: 'date'},
                {id: 'Duration', type: 'number'},
                {id: 'Percent Complete', type: 'number'},
                {id: 'Dependencies', type: 'string'}
            ],
            "rows": [
                {c: [
                    {v: 'Research'},
                    {v: 'Find sources'},
                    {v: new Date(2015, 0, 1)},
                    {v: new Date(2015, 0, 5)},
                    {v: null},
                    {v: 100},
                    {v: null}
                ]},
                {c: [
                    {v: 'Write'},
                    {v: 'Write paper'},
                    {v: null},
                    {v: new Date(2015, 0, 9)},
                    {v: daysToMilliseconds(3)},
                    {v: 25},
                    {v: 'Research'}
                ]}
        ]};

to display in html
` <div google-chart chart="myChartObject" style="height:600px; width:100%;"></div>`


but i get a invalid
![image](https://cloud.githubusercontent.com/assets/4823082/18328750/138491a6-7505-11e6-8b87-9666bd0d1e9a.png)

I dont´t know if not supported, or I missing something  to do this.?

I will apreciate your comments on this. and Thanks for this directive.

**Comment by brahalla** [comment]
Changing the chart type to `Gantt` should fix this; I had the same problem after the Google Charts library was recently updated:

`$scope.myChartObject.type = 'Gantt';`

**Comment by outis10** [comment]
Fixed, thanks again

**Comment by naveenjafer** [comment]
@brahalla  @outis10 Did the percentage work as expected for you? Even with the percentage being set to 50 percent and the start and end time being set as expected, the bar doesnt fill half as shown in the google chart tutorials.
