### ISSUE TITLE
Animation option not working

### ISSUE THREAD

**Issue by abartolo** [angular-google-chart/angular-google-chart#232]
Hello,

Thanks for the this project! I am having issues with animation. It isn't working as I follow the options in google charts API documentation.

Thanks,
Alex

**Comment by zarko-tg** [comment]
@abartolo You might want to provide a static or live example code to expand on your issue. It's always easier to help when there's something to see or reproduce.

**Comment by Balrog30** [comment]
I have tested animation in the past in response to issues. I do really need to see what you're trying to do to help you. A live code example like jsfiddle, plunker, or codepen really helps, too.

**Comment by nbering** [comment]
Closing, no response...
