### ISSUE TITLE
Coloring columns

### ISSUE THREAD

**Issue by hunkim** [angular-google-chart/angular-google-chart#234]
How can I set different colors for each bar like this?

https://developers.google.com/chart/interactive/docs/gallery/columnchart?hl=en

![image](https://cloud.githubusercontent.com/assets/901975/11332936/d273f4ec-9204-11e5-89d2-f924c2b4eb2a.png)

 "rows": [
        {c: [
            {v: "Mushrooms"},
            {v: 3},
            {v: 'color...'}
        ]},

does not work.

**Comment by radiohalo5** [comment]
Try this for your style column
{ 'role': 'style', 'type': 'string'  }

**Comment by Balrog30** [comment]
A beautifully composed question. Alas, I do not have the time at the moment to give it the detailed answer it deserved. @radiohalo5 is pointing you in the right direction. The given object literal it part of a column definition for column type you are looking for.

You can also pass the data in as the array structure shown in the documentation from Google.

**Comment by Balrog30** [comment]
@hunkim Did you manage to solve this, or do you need more help?

**Comment by hunkim** [comment]
I'm sorry, but I did not get the idea clearly. If you cam give me an
example, it would be very nice. Thanks!

**Comment by radiohalo5** [comment]
I think the problem might be in the way you are creating the style column. It's hard to know for sure because you didn't include your cols code. In my project it didn't work until I added type:'string' to the style column.

Try this:
```javascript
{"cols": [
        {id: "t", label: "Topping", type: "string"},
        {id: "s", label: "Slices", type: "number"},
        {role: "style", type: "string"}
    ], "rows": [
        {c: [
            {v: "Mushrooms"},
            {v: 3},
            {v: "silver"}
        ]},
        {c: $scope.onions},
        {c: [
            {v: "Olives"},
            {v: 31},
            {v: "gold" } 
        ]},
        {c: [
            {v: "Zucchini"},
            {v: 1},
            {v: "blue" }
        ]},
        {c: [
            {v: "Pepperoni"},
            {v: 2},
            {v: "green" }
        ]}
    ]
};
```

**Comment by hunkim** [comment]
@radiohalo5 It works! Thanks!!
