### ISSUE TITLE
Help: How can we call clearChart() to avoid memory leaks?

### ISSUE THREAD

**Issue by esteveavi** [angular-google-chart/angular-google-chart#239]
Help: How can we call clearChart() to avoid memory leaks?

**Comment by Balrog30** [comment]
Can you better describe when/why you need to do this? There are a few ways to get ahold of the chart object, but the most reasonable ways is to hook into the `ready` event with the [`agc-on-ready`](http://angular-google-chart.github.io/angular-google-chart/docs/0.1.0/directives/agcOnReady/) directive, and then store the chartWrapper for later use. The chartWrapper can be used to grab the inner chart object with `chartWrapper.getChart()`.

There might also be some ways to simply kill the whole directive and the chart with `ng-if`. Also, if you change the chart type, the chartWrapper kills the inner chart object and makes a new one. So if you can get it to change the chart type for one draw cycle and then change it back, you'll have a new chart object.

That being said, if you can give more information on when the chart needs to be cleared, I can maybe come up with a better solution, or add something to solve this issue.

I've been following the google charts issues, so I am aware that re-drawing the same chart is associated with a memory leak. That said, it's probably not a big deal unless you are keeping a chart around a updating it often over a period of time. I also get the impression that the memory leak issues should be resolved in the next version of the Google Charts API.

**Comment by esteveavi** [comment]
Hi,
Excuse me for the delay.  I was just trying to include 10 charts in the same page, and found that google charts made chrome and firefox crash because of a memory leak. 
I was just trying to find a way to avoid that.

Regards,

**Comment by nbering** [comment]
Closing as aged. I really hope they have that memory leak issue fixed by now. You're welcome to request I re-open if it's still a problem.
