### ISSUE TITLE
Scope isolation in the sub-directives

### ISSUE THREAD

**Issue by rixlabs** [angular-google-chart/angular-google-chart#241]
Still digging in the code and I found that in some sub-directives when you have to pass arguments to the callback funcition you do(I use agcOnReady as example):
```
scope.$apply(function (){
          scope.$eval(attrs.agcOnReady, {chartWrapper: chartWrapper});
});
```
Introducing a scope to the subdirectories you can obtain the same effect without the $apply and $eval code.

```
function onReadyDirective(){
        return {
            restrict: 'A',
            scope: {
                agcOnReady: '&'
            },
            require: 'googleChart',
            link: function(scope, element, attrs, googleChartController){
                callback.$inject=['chartWrapper'];
                function callback(chartWrapper){
                    scope.agcOnReady({chartWrapper: chartWrapper});
                }
                googleChartController.registerWrapperListener('ready', callback, this);
            }
        };
```

In this way you call the 'local function' agcOnReady passing the object chartWrapper by name and you have the same effect without the scope functions boilerplate.

There is a reason for having **scope: false** ?

If you're interested in the refactor I can create a pull request wit the mod on all the subdirectives.

**Comment by Balrog30** [comment]
Thanks, but yes. As I mentioned in #240, one $scope per element makes this more complicated than it seems.
