### ISSUE TITLE
Loading several charts on one page

### ISSUE THREAD

**Issue by snothegg** [angular-google-chart/angular-google-chart#244]
Hi 

We have an issue with loading several charts on the same page
The issue is that very often only one of them shows up
https://www.sharewise.com/us/markets/fundamental_comparison

The strange thing with this issue is that it works sometimes works so maybe there is some timing issue when the charts are initialized

before we dig deeper I wanted to ask if there are any know issues with loading several charts on same page?

Thx

**Comment by Balrog30** [comment]
The only thing that comes to mind immediately is google/google-visualization-issues#2066. Do you happen to be using Material Design charts?

**Comment by Balrog30** [comment]
I poked around a little to see if there was anything obvious. Your source is minified, so I couldn't see a whole lot that was helpful, but I did notice that if I sat on the page long enough there would be some more http traffic with callbacks in the URL, and then some more of the charts would load. Perhaps it's an issue moving data around in your app? I'd need to see more code to be sure, but I'd start by sticking some verbose log statements in wherever you're handling the chartObject or it's data.

**Comment by Balrog30** [comment]
Oh, I'm also noting that you've moved to 0.1.0 and there's some breaking changes with event attributes. Basically everything but `google-chart` and `chart=` had `agc-` added to the beginning. It was in the release notes and was part of why I kept it in beta for a couple months before pushing as an official release.

**Comment by Balrog30** [comment]
Ok, now I feel like I'm just ripping apart your code, but I'm also noticing that you have an element a couple of levels above the chart likes this:
```HTML
<div config="chartConfig" id="histogram">...</div>
```
The potential problem I see is that the `id="histogram"` is repeated on the page several times. I suspect you're using ID as an attribute for a directive, but `id` also had meaning for the browser, and ID's are meant to be unique. I have no idea what this would actually do, but I can imagine it causing silent failures.

**Comment by Balrog30** [comment]
Maybe forget that last one about ID. Looks like Google Charts is rendering an empty block, but no chart. That takes me back to the contents of the chartObject, or the event handlers.

**Comment by snothegg** [comment]
Hi 
thx very much for your help 
I think its related to this google/google-visualization-issues#2066
The data is definitely there and it also worked for a long time

I already tried to use the static google charts but a short attempt with this change did not help (actually now no charts are shown anymore, google charts is loaded)

Sorry for the confusion with the id and chartConfig,thats actually a left over from Highcharts we used before.

Best
 

```
-
-            window.google.load('visualization', apiConfig.version, settings);
+            window.google.charts.load("43", {packages:["bar", "corechart", "line"]})
+            // window.google.load('visualization', apiConfig.version, settings);
         };
         var head = document.getElementsByTagName('head')[0];
         var script = document.createElement('script');

     function googleJsapiUrlProvider() {
         var protocol = 'https:';
-        var url = '//www.google.com/jsapi';
-
+        // var url = '//www.google.com/jsapi';
+        var url = '//www.gstatic.com/charts/loader.js'
         this.setProtocol = function (newProtocol) {
```

**Comment by Balrog30** [comment]
So, as I understand the diff snippet you put at the end of your comment, you switched to the new Frozen versions of the google charts API? Was this before or after your issue? If it was after, did it solve the problem?

**Comment by snothegg** [comment]
Hi 

the diff I did was just a quick test on my local machine. Unfortunately it actually worsened the problem
as no charts were working anymore . 
https://github.com/google/google-visualization-issues/issues/2066 last comments

In production all charts are working, only places where we use several material charts now fail

Best

**Comment by Balrog30** [comment]
I'm pretty sure the issue is with material charts as in the google.charts.* namespace. There was an option flag somewhere to apply a theme like the material design without actually switching to the new charts constructors. Have you tried that? Also, there might be a little more involved in loading the frozen I believe @moustacheful got this working on his fork of the repo, but it's a couple of months behind, so I can't do a quick merge. I'd have to take the same ideas and rewrite it. It's in my plans, but I haven't had time to support that feature, yet.

**Comment by snothegg** [comment]
Thx, I think i found the issue
in the past we had to load bar + corecharts, now if you load both there is this issue
just loading corecharts seems to solve it, the features we needed from material charts (stacked bar charts) also still work

Thanks again for your help!!

**Comment by Balrog30** [comment]
Not a problem. Always happy to help.

**Comment by boltex** [comment]
hey @snothegg  check out #267 in order to use the new libs 'gstatic' . Your modification did not work because you did not add the callback :

window.google.charts.setOnLoadCallback( settings.callback );

Have a nice day ! :)

**Comment by longzheng** [comment]
I'm also experiencing this problem. I use ```['corechart', 'table', 'geochart']```
