### ISSUE TITLE
How to specify a date formatter for an area chart?

### ISSUE THREAD

**Issue by rj93** [angular-google-chart/angular-google-chart#245]
I am having trouble specifying how to use a custom date formatter for an area chart.

My current code is:
chart.formatters = {"DateFormat" : {"pattern" : "HH:mm:ss dd:MM:yy"}};

But this produces the error: self.iFormats[formatType] is undefined.

How are you supposed to supply the infomation?

Thanks!

**Comment by rixlabs** [comment]
you can pass'it like this:
```
var formatters = {
            date: [{
                columnNum: 1,
                pattern: "HH:mm:ss dd:MM:yy"
            }]
        }

        var chartItem = {
            data: data,
            type: 'AreaChart',
            formatters: formatters
        };
```

chartItem is the object you pass to the directive.

Hope that this is what you're searching

**Comment by rixlabs** [comment]
For the axis you can apply the same pattern like this:

```
var chartItem2 = {
            data: data2,
            type: 'AreaChart',
            formatters: formatters,
            options:{vAxis: {format:"HH:mm:ss dd:MM:yy"}}
        };
```

**Comment by rj93** [comment]
Thank you, the first solution worked for me
