### ISSUE TITLE
Missing license file.

### ISSUE THREAD

**Issue by jose-goncabel** [angular-google-chart/angular-google-chart#248]
I have been trying to find a copy of the license for this software but it seems the file does not exist yet.

Can you put a copy of it?

Much appreciated.

**Comment by Balrog30** [comment]
Technically, it's not up to me to do so, the project was originally created by @bouil, so while I have made significant contributions, the original work is his copyright. He put `lisence: "MIT"` in the package.json, but you're probably right, without the actual license statement in the repository, that's not exactly binding. You can safely assume his intent based on that, though.

**Comment by Balrog30** [comment]
In #108 @bouil states that the license is declared in the file header. This is still true of the unminified version of the compiled source. I'll contact @bouil directly to ask him to add an official declaration of the MIT license in the repository.

**Comment by jose-goncabel** [comment]
Thanks a million.
