### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by Abrissirba** [angular-google-chart/angular-google-chart#256]
It would be nice if there was a typescript definition file for angular-google-chart, https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by nbering** [comment]
I'm planning on migrating to typescript at some point soon, but need some free time to do free work.

I would note that most of what you'd want typings for is actually under the Google Charts API, which is an entirely separate project. From what you consume publicly with Angular-Google-Chart, there might be something like 3 or 4 interfaces that are actually part of this project.

**Comment by nbering** [comment]
I got started on the TypeScript conversion this weekend. The actual Angular Google Chart typescript code needs a bit more cleanup before I commit it, but I posted my work-in-progress for a Google Charts API type definition at https://github.com/angular-google-chart/google-chart-typings. It's very incomplete, but it's got enough of the API defined to get Angular Google Chart to build, plus a little more. No visualizations, yet. It's mostly helper libraries.

It has a `typings.json` so you can consume it with [Typings](https://github.com/typings/typings) like this:
```
typings install github:angular-google-chart/google-chart-typings --ambient --save
```
Please don't report this to the Typings Registry just yet, it's not really ready for general use. I'll register it when it's mostly complete.

When I get the typescript version of Angular Google Chart going I'll include a `typings.json` file.
