### ISSUE TITLE
How Google chart can run locally in anguarjs application ?

### ISSUE THREAD

**Issue by santosh-k1** [angular-google-chart/angular-google-chart#259]
Hi i have used ng-google-chart.js file in my angularjs application . There is an path set of  var url = '//www.google.com/jsapi'; which create some issue and not loaded properly every time. the code are as below -
```
 /* global angular */
(function(){
    angular.module('googlechart')
        .provider('googleJsapiUrl', googleJsapiUrlProvider);
        
    function googleJsapiUrlProvider() {
        var protocol = 'https:';
        var url = '//www.google.com/jsapi';
        
        this.setProtocol = function (newProtocol) {
            protocol = newProtocol;
        };

        this.setUrl = function (newUrl) {
            url = newUrl;
        };

        this.$get = function () {
            return (protocol ? protocol : '') + url;
        };
    }
})();
```
Can you tell me that how we can this above link locally so that i can load properly

**Comment by nbering** [comment]
Saving the code fetched by the google loader is a violation of their terms of service, so there's no option to do so. They have changed to a new loader endpoint, but loading from that endpoint requires a small change to our code. It's on my roadmap for the next version, but to be honest I'm spending more time on this project giving people support than I do coding these days.

If it's not an issue for your application, some people have had some luck switching to http. Try this:

```JavaScript
angular.module('YourApp', ['googlechart'])
  .config(function(googleJsapiUrlProvider) {
    googleJsapiUrlProvider.setProtocol('http:');
  });
```

**Comment by laviyatziv** [comment]
Try `http://lvh.me:8000` it's a clever dns service that mimics your `http://localhost:800`.

**Comment by nbering** [comment]
@laviyatziv Perhaps I'm missing something, but I don't see the relevance to the issue. You can't host the Google Visualization API yourself for whatever reason. Not a technical limitation, but a licensing issue. If hosting the file yourself is a requirement, then you'd need a different library.

**Comment by laviyatziv** [comment]
I suspected that the issue that @santosh-k1 is having is because of a CORS (Cross-origin resource sharing) limitation. Using `http://lvh.me:8000` circumvents this limitation.

**Comment by nbering** [comment]
Beyond changing the protocol, and the related issue of loading from the new "gstatic" endpoint, changes to the loader behaviour are unsupported due to Licensing constraints. Closing as unsupported.

**Comment by boltex** [comment]
hey @santosh-k1   check out https://github.com/angular-google-chart/angular-google-chart/issues/267 in order to use the new libs 'gstatic' . Your modification did not work because you did not add the callback : 

` window.google.charts.setOnLoadCallback( settings.callback );`

Have a nice day !  :)
