### ISSUE TITLE
Export chart to pdf

### ISSUE THREAD

**Issue by yong86** [angular-google-chart/angular-google-chart#260]
Hello,

Can i export the charts to pdf?

**Comment by nbering** [comment]
There's nothing built-in to do this, and I personally have no interest in writing a feature for it.

If you just need something one time, use a print to PDF driver, most new operating systems seem to come with one.

If you need to automate it, maybe try something like PhantomJS.  I caution though that I am familiar with this method only from people reporting that they have issues with it in the broader Google Charts community, so my impression is that it is quite error-prone.

If you have nothing written right now, and only need PDFs, I would advise looking for a chart solution that is specifically intended for PDF output. I know they're out there for the .NET and Java world, not sure what is available for JavaScript at this time.

**Comment by mllobere** [comment]
I export pdf using jsPDF. I add the "agc-on-ready" directive to my chart, and get the imageURI from the chartWrapper (chartWrapper.getChart().getImageURI()). I save this URI somewhere on my $scope. (I actually add it to another field of my chartObject). On PDF export, I just get the URI from my object. This seems to be working ok. Just watch-out for the size as it might look blury on PDF if resolution is too low. I am not sure if this is the proper way to do that, but its working ok.

**Comment by nbering** [comment]
Resolved, and out of scope for adding as a guide to documentation.
