### ISSUE TITLE
Problem with ng-switch

### ISSUE THREAD

**Issue by garciaba** [angular-google-chart/angular-google-chart#262]
I am facing a problem that seems to appear when using `ng-switch` with angular-google-chart. I'm quite to new to AngularJS so I don't know if it is my problem or an actual bug.
For your information, I am using the template from here: http://startangular.com/product/sb-admin-angular-theme/

This were my steps: 
1. `$ bower install angular-google-chart#0.1.0 --save`
2. On my index.html, I added `<script src="bower_components/angular-google-chart/ng-google-chart.js"></script>`
3. On my app.js, I wrote the following:

```
    .module('sbAdminApp', [ //setting a module
    'oc.lazyLoad',
    'ui.router',
    'ui.bootstrap',
    'angular-loading-bar',
    'googlechart'])
    .config(['$stateProvider', '$urlRouterProvider', '$ocLazyLoadProvider', function ($stateProvider, $urlRouterProvider, $ocLazyLoadProvider) {
```

and

```
.state('dashboard.form', {
                templateUrl: 'views/form.html',
                url: '/form',
                resolve: {
                    loadMyFiles: function ($ocLazyLoad) {
                        return $ocLazyLoad.load({
                                name: 'googlechart',
                                files: ['bower_components/angular-google-chart/ng-google-chart.js']
                            }),
```
1. on my form.js, I have: 

```
var wrapper = new google.visualization.ChartWrapper({
                chartType: 'LineChart',
                options: options,
                dataTable: data,
                containerId: 'line-example'
            });
```

and

```
wrapper.draw();
```

What drives me crazy is that this WORKS:

```
<div class="panel-body">
                <div google-chart class="chartObject" agc-on-select="selectHandler(selectedItem)" id="line-example"> </div>
                <div id="png"></div>
            </div>
```

but if I change it to this:

```
<div ng-switch="dropdownData.selectedOption.id" class="panel-body">
    <div ng-switch-when="1">
        <div google-chart class="chartObject" 
        agc-on-select="selectHandler(selectedItem)"id="line-example"></div>
    </div>
    <div ng-switch-when="2">
     TEST2
    </div>
    <div ng-switch-when="3">
      TEST3
    </div>
</div>
```

It throws the following error: `ReferenceError: google is not defined`, whose trace show an error here: `var data =  google.visualization.arrayToDataTable(valoresTabla);
`
The whole trace looks like this:

```
    at form.js:215
    at u (angular.js:11319)
    at angular.js:11405
    at h.$eval (angular.js:12412)
    at h.$digest (angular.js:12224)
    at h.$apply (angular.js:12516)
    at f (angular.js:8204)
    at F (angular.js:8412)
    at XMLHttpRequest.x.onreadystatechange (angular.js:8351)
```

**Comment by nbering** [comment]
The google visualization API is itself loaded asynchronously, so you'll need to wait for the library to load to call any of it's methods. See http://angular-google-chart.github.io/angular-google-chart/docs/0.1.0/services/googleChartApiPromise/.

There is some other weird stuff going on in your code, but I don't really know where to begin and what effects they'll have on the big picture. The biggest thing is that you have a chart being manually created on the same element as the google-chart directive. So... I have no idea what that would actually do. You're effectively pointing two ChartWrappers at the same element.

**Comment by nbering** [comment]
No response from original poster. Closing as aged.
