### ISSUE TITLE
Can't get on-ready to work 

### ISSUE THREAD

**Issue by jsiegmund** [angular-google-chart/angular-google-chart#263]
For some reason I cannot get the on-ready samples to work. Probably not a bug but an issue on my side, but would be awesome if you could take a look. 

I tried the out of the box example: 

`vm.myReadyCallback = function (chartWrapper) {
     console.log('test');
};`

And:

`<div google-chart chart="vm.tempChartObject" style="height:300px; width:100%;" on-ready="vm.myReadyCallback(chartWrapper)"></div>`

As you can see, I'm using vm as my viewmodel object, so in the route there's controllerAs: "vm". This is working fine for the chart object. As I suspected that might be the problem, I tried with and without and also tried binding the callback function to $scope instead. I tried all combinations possible, none of them work. The chart is rendered and everything works ok, the callback is never called (no visible errors either). I was hoping I could get a callback after the chart has finished rendering. What am I missing here?

**Comment by nbering** [comment]
`on-ready` to changed to `agc-on-ready` in 0.1.0 to resolve naming conflicts with ui-bootstrap directives. Could that be the problem?

**Comment by jsiegmund** [comment]
That's definitely the problem, thanks. Is there a good reference somewhere where the most actual properties can be found?

**Comment by jsiegmund** [comment]
Ok so the event now works but my problem isn't solved. Perhaps you have a good idea. I'm using the graphs inside a Cordova app. I've got a tabbed view with similar graphs in each tab. When switching tabs, I need to load data first and so I want to display a loading indicator before the graph is ready for display. So the flow is: 

- User selects a different tab
- Tab view should switch
- Content should display loading indicator
- When graphs are fully loaded and rendered, the loading indicator disappears and the graphs are displayed

What would be a good way to do this?

**Comment by nbering** [comment]
Are you using Ionic? Makes a difference for what you might have out of the box.

If using Ionic I would make each chart in a view, add your data fetching as a route-resolve for ui-router, and hook into the route change events to use the $ionicLoading service to show a spinner while the loadings takes place.

**Comment by jsiegmund** [comment]
Nope, using Angular Material, not Ionic.

**Comment by nbering** [comment]
Apologies then, your implementation question is pretty general and I'm not sure what to suggest. If you run into issues with anything to try, feel free to raise an issue or ask in the [gitter.im](https://gitter.im/angular-google-chart/angular-google-chart) chat room. There's probably a hundred different combinations of ways to achieve your desired result.

**Comment by jsiegmund** [comment]
Ok I understand. No need for apologies btw, great that you could help me out. I'm sure I'll find a proper way of doing it :) Thanks again!
