### ISSUE TITLE
how to set animation options

### ISSUE THREAD

**Issue by ulise** [angular-google-chart/angular-google-chart#265]
Hi,
I´m trying to get a google-chart animation running. 
Using the pie sample I set the following options.

```
$scope.chartObject.options = {
      title: 'How Much Pizza I Ate Last Night',
      pieHole: 0.9,
      animation: {
        duration: 1000,
        easing: 'out',
        startup: true
      }
    }; 
```
but could not get any animation running. 
The project is build with yeoman and the plugin is added using bower.
Is there a sample with animation around?
Many thanks,
Uli

**Comment by nbering** [comment]
Animation is not listed as a supported option for pie charts. See the [pie charts documentation](https://developers.google.com/chart/interactive/docs/gallery/piechart#configuration-options).

**Comment by ulise** [comment]
Ahh, sorry.
