### ISSUE TITLE
How to use the 'gstatic' version of google charts ?

### ISSUE THREAD

**Issue by boltex** [angular-google-chart/angular-google-chart#267]
Hi Nic!  :)

Old lib : https://jsfiddle.net/m7ro6c0s/3/

New lib: https://jsfiddle.net/wrk3ua97/

the labels on the right of the bars are much more elegantly handled. How can I use this ? 

Thanks for a great angular wrapper ! 
[edit: fixed links]

**Comment by boltex** [comment]
FOUND OUT MYSELF !! 
of course, at around line 800, change the url like this: 
```
        // var url = '//www.google.com/jsapi';
        var url = '//www.gstatic.com/charts/loader.js';
```
and at around line 460, comment out the old "window.google.load" line and add those lines: 

```
            settings = angular.extend({}, apiConfig.optionalSettings, settings);
               window.google.charts.load('current', {packages: ['corechart']} );
               window.google.charts.setOnLoadCallback( settings.callback );

            // window.google.load('visualization', apiConfig.version, settings);
```
(notice the 'on load callback' line I added.)
So there! See ya later guys !! :)

**Comment by belgi** [comment]
I would change one line to  : window.google.charts.load('current', settings );

so this line code works better.

.value('googleChartApiConfig', {
    version: '1.1',
    optionalSettings: {
      packages: ['corechart','line'],
      language: 'en'
    }
  });

**Comment by kjholla** [comment]
Can this be controlled via a configuration parameter similar to 'googleJsapiUrl'? That way, the module would still be usable via npm install and not need a code modification with every deployment.

Thanks,
KH

**Comment by nbering** [comment]
@kjholla No, unfortunately that will not work, as the loader functions are called on a different object, which breaks old loader code. I've got some work in progress to update to the new loader, but honestly it's never been a high priority since all the old code still works fine.

**Comment by San-Jeevan** [comment]
if anyone want to use to geochart with this solution and sees maps api error, solution i've implemented is this:

```
            settings = angular.extend({}, apiConfig.optionalSettings, settings);
            **if (settings.packages.indexOf("geochart") !== -1) {
                settings.packages.mapsApiKey = 'YOUR_API_KEY';
            }**

            window.google.charts.load('current', settings);
            window.google.charts.setOnLoadCallback(settings.callback);
```

**Comment by mribichich** [comment]
@nbering Are you planning on adding this new way of calling the static version:

`window.google.charts.load('current', settings);`

Because this one doesnt work any more with the last version:

`window.google.load('visualization',  `

thanks!

**Comment by nbering** [comment]
See #310. This feature is currently available on the development branch. Planning a 1.0.0-beta.1 release very soon.
