### ISSUE TITLE
Redraw event

### ISSUE THREAD

**Issue by sigMacity** [angular-google-chart/angular-google-chart#269]
It would be very useful to be able to ping off a redraw event that is handled up by the google chart directive to cause the chart to redraw itself.

As an example of when this would be useful:

Having a chart inside an ng-show directive causes problems when the chart is not initially shown until the ng-show becomes true. In which case the chart is often drawn the wrong size and is only resized correctly when the window or chart container is manually resized. Being able to send a redraw event when the ng-show state changes would be a simple solution to this problem.

**Comment by nbering** [comment]
You can use ng-if instead of ng-show to prevent the chart from drawing until displayed. If you need to trigger a redraw of all charts for some other reason, broadcast `resizeMsg` and it will behave as if the window was resized and redraw all charts.

**Comment by sigMacity** [comment]
Will give it a try. Thanks very much for the prompt reply.

Graham

On 11 April 2016 at 22:52, Nicholas Bering <notifications@github.com> wrote:

> You can use ng-if instead of ng-show to prevent the chart from drawing
> until displayed. If you need to trigger a redraw of all charts for some
> other reason, broadcast resizeMsg and it will behave as if the window was
> resized and redraw all charts.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-google-chart/angular-google-chart/issues/269#issuecomment-208578071>
>



-- 


*Defining the future of retail investor interaction*.

This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of sigMacity Limited.
If you are not the intended recipient of this email, you must neither take
any action based upon its contents, nor copy or show it to anyone. Please
contact the sender if you believe you have received this email in error.

**Comment by nbering** [comment]
Oh ya, I forgot about the other strategy. If you want just one chart to redraw, change some meaningless option on the chart's options. Like `options: {redrawTrigger: 0};` and then `redrawTrigger++`. Then just that chart will redraw. But personally, I just use ng-if. You'd need this approach if you're resizing individual elements, or ng-if isn't an option, for performance reasons perhaps.

**Comment by sigMacity** [comment]
Your original solution works perfectly, though I'll keep in mind what
you've just said.

I was using the Angular UI tab directives, which I guess use ng-show or
similar internally and hence my problem. As soon as I re-coded a tab like
solution that uses ng-if your solution worked.

Again many thanks.

On 11 April 2016 at 22:57, Nicholas Bering <notifications@github.com> wrote:

> Oh ya, I forgot about the other strategy. If you want just one chart to
> redraw, change some meaningless option on the chart's options. Like options:
> {redrawTrigger: 0}; and then redrawTrigger++. Then just that chart will
> redraw. But personally, I just use ng-if. You'd need this approach if
> you're resizing individual elements, or ng-if isn't an option, for
> performance reasons perhaps.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-google-chart/angular-google-chart/issues/269#issuecomment-208579269>
>



-- 


*Defining the future of retail investor interaction*.

This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of sigMacity Limited.
If you are not the intended recipient of this email, you must neither take
any action based upon its contents, nor copy or show it to anyone. Please
contact the sender if you believe you have received this email in error.

**Comment by nbering** [comment]
Glad that worked for you. You're welcome to ask more questions anytime.
