### ISSUE TITLE
How to color each column in a column chart ?

### ISSUE THREAD

**Issue by GBora** [angular-google-chart/angular-google-chart#271]
I'm trying to color each column in a column chart differently, reading the documentation on google charts tells me that this should be possible but I can't figure out how to build my rows so that I can place a different color on each of them.

Code sample:
`    var collsArray = [];
    var rowsArray = [];

```
for (var i = 0; i < vm.projects.length ; i++) {

    rowsArray.push({
         "c": [
            {
                "v": vm.projects[i].name
            },
            {
                "v": vm.projects[i].developers,
                "f": vm.projects[i].developers + ' developers working on ' + vm.projects[i].name
            }]
    });

}
collsArray = [{id: 'project', label: 'Project', type: 'string'},
       {id: 'developers', label: 'Developers working', type: 'number'}];

vm.chartProjects = {
      "type": "ColumnChart",
      "displayed": false,
      "data": {
        "cols": collsArray,
        "rows": rowsArray
      },
      "options": {
        "isStacked": "true",
        "fill": 0,
        "width": '100%',
        "height": '100%',
        "displayExactValues": true,
        "chartArea": {
            "left": "1%",
            "top": "1%",
            "height": "98%",
            "width": "98%"
        }
      },
      "formatters": {},
      "view": {}
};`
```

**Comment by nbering** [comment]
`chartObject.options.colors = ["red", "#000044"];`

The colors option takes an array or color values.  If you only give it one value, all columns will be the same. If you assign 3 values and 6 columns, each colour will repeat twice.

**Comment by GBora** [comment]
@nbering thanks for the prompt answer but I just tried with your colors array, every column is red blue isn't used at all.

**Comment by nbering** [comment]
Odd. All I can do is point you here: https://developers.google.com/chart/interactive/docs/gallery/columnchart#configuration-options

I don't write the chart rendering, this project is just a wrapper to make it more convenient to work with the Google Charts API from Angular.

**Comment by nbering** [comment]
@GBora Did you get this working in the end? Just wondering if I can close this to clean it up. If a resolution was found found it might be nice to share for anyone who encounters your issue.

**Comment by tavai89** [comment]
+1

**Comment by nbering** [comment]
@tavai89 If you can link a demo or past some code with what you have now, I might be able to help diagnose the issue. Just saying +1 doesn't give me anything to work with.

**Comment by GBora** [comment]
@nbering I'm sorry to say the requirements changed and I didn't need to complete the chart anymore, I don't have access to the code anymore but I remember not being able to get it right.
