### ISSUE TITLE
Error using geochart

### ISSUE THREAD

**Issue by ysilvela** [angular-google-chart/angular-google-chart#277]
I obtain this error when I load the map. The map loads fine but the rest of javascript stop and some funcionalities not shown. 

TypeError: $elem[0].getContext is not a function

Thanks.

**Comment by nbering** [comment]
A quick text search of our code for `$elem[0].getContext` does not return any results, and that function does not sound familiar. More information would be helpful.

- Does the error provide a line number?
- What version of angular-google-chart are you using?
- What version of angular?
- Are you using any other third-party angular directives (particularly on the same element as your chart)?
- What browser and version?
- Can you provide an example on [jsFiddle](https://jsfiddle.net), [plunker](http://plnkr.co), or [CodePen](http://codepen.io) that demonstrates this error?

**Comment by nbering** [comment]
No response from original poster. Closing as aged.
