### ISSUE TITLE
Lenguage selection

### ISSUE THREAD

**Issue by adussarpsbcg** [angular-google-chart/angular-google-chart#279]
It would be nice to have a lenguage selection for the chart as a config parameter.
It can be done by changing the loading lenguage of google vizualisation.
"google.load('visualization', '1', {'packages':['corechart'], 'language': 'ja'});
".

**Comment by nbering** [comment]
You already can. Check the [googleChartsApiConfig value documentation](.http://angular-google-chart.github.io/angular-google-chart/docs/0.1.0/values/googleChartApiConfig/)

**Comment by adussarpsbcg** [comment]
Ok, I saw this in the code ay, did found this easily on the doc that's all.
Thanks!
