### ISSUE TITLE
It appears the gauge example is broken in the documentation.

### ISSUE THREAD

**Issue by jrodenbostel** [angular-google-chart/angular-google-chart#282]
http://angular-google-chart.github.io/angular-google-chart/docs/latest/examples/gauge/

Instead of the gauge, we see: "You called the draw() method with the wrong type of data rather than a DataTable or DataView"

**Comment by nbering** [comment]
Works on my machine.™️

What browser are you using?

**Comment by jrodenbostel** [comment]
Chrome Version 51.0.2704.103 (64-bit) on OS X 10.11.5.

I updated Chrome to 51.0.2704.106, cleared the cache, closed active browsers, etc.  Seems to work now. Sorry for the hassle.

Never stopped working in Safari, though.

**Comment by nbering** [comment]
You're not the first to report an error like that. Might be something with caching and the google api loader.

**Comment by jrodenbostel** [comment]
This helps my self esteem.  Thank you.
