### ISSUE TITLE
Using Analytics Embed API cause intermittent problem 

### ISSUE THREAD

**Issue by tthiatma** [angular-google-chart/angular-google-chart#283]
![2016-07-08_9-51-21](https://cloud.githubusercontent.com/assets/4022533/16695881/f2ed1bfe-44f6-11e6-918f-1fa18f1b62c3.png)
When mixing angular google chart with analytics embed api, sometimes it will throw error saying 
"You called the draw() method with the wrong type of data rather than a DataTable or DataView"

plnkr:
http://plnkr.co/edit/vKjts4KpqnjePgnsMogC?p=preview

quote from Nicholas (author):
It would only happen if both libraries have tried to call load in the window before one gets it to load. Like:
Analytics Requests
Google Charts Requests (over-writing callback)
Library Loads, Call Charts Callback

**Comment by nbering** [comment]
Discussed on Gitter, [July 8th, 2016](https://gitter.im/angular-google-chart/angular-google-chart/archives/2016/07/08). Requires authorization to google analytics data and refresh after authorization. Works fine when you first login.

**Comment by nbering** [comment]
This seems to have been fixed upstream. The original plunker meant to reproduce the issue works fine for me now.
