### ISSUE TITLE
Gauge problem with multiple chart application

### ISSUE THREAD

**Issue by mjaiswalpq** [angular-google-chart/angular-google-chart#284]
I have an application with multiple angular google chart(column, pie, gauge etc.). I noticed sometimes Gauge shows below message-
"You called the draw() method with the wrong type of data rather than a DataTable or DataView"

All other charts gets created fine.

I tested the same on chrome(works fine 50% times) and on firefox(works fine 90% times). Is it related to 'google.visualization.arrayToDataTable'?

Am I missing something in my code?

**Comment by nbering** [comment]
I've had a couple random reports of something like this. Clearing the browser cache seems to help. I haven't seen it myself.

**Comment by mjaiswalpq** [comment]
Well initially it worked well for me too and now when my application is almost completed and I am ready to demo the same to the stakeholders, I am facing this problem.  

I don't want this to appear while I am presenting my application. Do you suggest to use 'google.visualization.arrayToDataTable'  to fix this issue? If yes, please suggest me how can I use the same.

**Comment by mjaiswalpq** [comment]
Tried doing cache clear but still facing the same problem. This comes and goes(one day works and not other day) without doing any changes in the code and does not look like a cache issue. Happening both on Firefox and Chrome. Looks like some sequential load issue.

Tried re-producing the same on plunker but found it working fine everytime. Not sure if it has to do anything with 'google.visualization.arrayToDataTable'.

Can anyone help if already faced similar issue and has a solution.

**Comment by raygig** [comment]
I have 3 Google Gauge charts on one page and every now and then this error will appear and the gages will not show. The code does not change just visiting the page is what triggers this. It happens about 20% of the time randomly. 

What does fix this is a hard refresh. Still no viable fix so for now I am using a different gauge library.

Uncaught ReferenceError: gvjs_wq is not defined
    at eval (eval at google.loader.eval.visualization (format+en,default+en.I.js:516), <anonymous>:2:30)
    at Object.google.loader.eval.visualization (format+en,default+en.I.js:516)
    at evalOrDefer (gauge+en.js:1)
    at gauge+en.js:1
    at gauge+en.js:1

**Comment by nbering** [comment]
@raygig Looks like an upstream issue. If I get a chance I'll take a look at https://github.com/google/google-visualization-issues to see if anyone has reported similar.

**Comment by raygig** [comment]
Went to that page and cant see what you are referring to.

![image](https://cloud.githubusercontent.com/assets/1569098/21693482/23244040-d34f-11e6-98fb-6effc4ac481a.png)

**Comment by nbering** [comment]
@raygig Google just uses that repo for the issues.

**Comment by raygig** [comment]
Ah yes I understand now. 

Thank You

**Comment by nbering** [comment]
Closing as upstream and aged.
