### ISSUE TITLE
Calendar chart support

### ISSUE THREAD

**Issue by fernandodof** [angular-google-chart/angular-google-chart#286]
I'm trying to create a Calendar Chart but it's not working. 
I saw this https://github.com/angular-google-chart/angular-google-chart/issues/209 but I didn't know where to put it.

I'm getting **"Invalid visualization type: CalendarChart"**

Can anyone help me ?

I tryed this, but no luck
```javascript
app.value( 'googleChartApiConfig', {
    version: '1.1',
    optionalSettings: {
        packages: [ 'calendar' ]
    }
} );
```
Thanks.

**Comment by nbering** [comment]
The constructor name for calendar charts is `Calendar`, so make sure your chart object has something like:

```js
$scope.myChartObject.type = "Calendar";
```

It looks like you probably have `CalendarChart` instead.

**Comment by fernandodof** [comment]
Thanks @nbering That worked, now I'm just looking for example object used to create the calendar chart.
And this https://google-developers.appspot.com/chart/interactive/docs/gallery/calendar didn't really help with that. Do know where I can find this object example ?

**Comment by nbering** [comment]
The link you gave is the authoritative example, I'm afraid. I could possibly transpose that to one of the other accepted formats for you if you'd like, but I won't have time to do that until later tonight.

If it helps any, the directive can handle any of these data formats:

- a 2d-array as would be given to [`google.visualization.arrayToDataTable()`](https://developers.google.com/chart/interactive/docs/reference#arraytodatatable)
- a Google [DataTable](https://developers.google.com/chart/interactive/docs/reference#DataTable) object literal
- an instance of `google.visualization.DataTable`

That last one is what they're using in the calendar examples. You can create one by using the [`googleChartApiPromise`](http://angular-google-chart.github.io/angular-google-chart/docs/latest/services/googleChartApiPromise/) provided by this library.

**Comment by fernandodof** [comment]
Meanwhile I will keep trying some other ways you mentioned

**Comment by fernandodof** [comment]
@nbering I got it working by creating an object literal with the following format:

 ```javascript 
self.reportCalendarChart = {
        type: 'Calendar',
        data: {
            cols: [
                { type: 'date', id: 'date' },
                { type: 'number', id: 'amount' }
            ],
            rows: [ {
                    c: [
                        { v: new Date( 2010, 0, 1 ) },
                        { v: 500 }
                    ]
                }, {
                    c: [
                        { v: new Date( 2010, 6, 1 ) },
                        { v: 1500 }
                    ]
                }, {
                    c: [
                        { v: new Date( 2010, 7, 10 ) },
                        { v: 2000 }
                    ]
                }, {
                    c: [
                        { v: new Date( 2010, 8, 20 ) },
                        { v: 5000 }
                    ]
                }

            ]
        },
        options: {
            title: 'Report Calendar'
        }
};
```

Thanks @nbering you helped a lot.

**Comment by nbering** [comment]
You're welcome.

**Comment by nphippen** [comment]
@fernandodof can you share an example of how you got this to work?  I am having the same error:
Invalid visualization type: Calendar

Please help!

**Comment by fernandodof** [comment]
HI @nphippen It's on my last comment. I just added the html part now. If you need any help please tell me.
