### ISSUE TITLE
Pie chart legend auto cut off

### ISSUE THREAD

**Issue by taudienkk** [angular-google-chart/angular-google-chart#291]
I have a pie chart that display in the small container, the legend is cut off when there is many items. Do we have any option to make each legend display in separate row?
![piechart](https://cloud.githubusercontent.com/assets/16218110/18506584/f2991ac4-7a96-11e6-9956-00ee836aac75.PNG)

**Comment by nbering** [comment]
Sorry for the late reply. This is an upstream feature of [Google Charts](developers.google.com/chart). See the [Pie Chart Options](https://developers.google.com/chart/interactive/docs/gallery/piechart#configuration-options) for all available configuration options. The one I think is relevant for you is `legend.maxLines`. There is also a note on that option that says maxLines is only respected when using `legend.position = 'top'`.
