### ISSUE TITLE
Stacked bar Chart

### ISSUE THREAD

**Issue by dreweird** [angular-google-chart/angular-google-chart#292]
How to display two stacked bar chart in one axis...i tried series option targetAxesIndex but it did not work

**Comment by nbering** [comment]
I'm sorry, but I really can't picture what you're describing. Can you include a sketch or example of another type of chart doing what you want?

**Comment by nbering** [comment]
It's been more than a month since you asked this, I'm assuming you found a solution or moved on.

**Comment by Albhaku** [comment]
![image](https://user-images.githubusercontent.com/15705961/43017006-496f7d66-8c1a-11e8-91b5-e6f240f06b90.png)

Hi, Nico, I think he was refering to this one. And I'm also getting a lot of troubles to make it work. I'm loading the Bar package, but still unable to get it.

**Comment by nbering** [comment]
@Albhaku Where does the sample image come from? What have you tried so far? I might be able to help as long as I have something to start with.

**Comment by Albhaku** [comment]
Hi, I got the example from here:

http://jsfiddle.net/p7o0pjgg/

It's an option for getting stacked columns for two sets of information. I think the example is pretty clear, cause I could confuse, haha, thanks.

I've tried the axis options, like the example, but couldn't get on. And thats all. I actually tried with the two extra charts you add, the material Bar chart, but still not working.
