### ISSUE TITLE
A stupid but very relevant question

### ISSUE THREAD

**Issue by achoudhurys** [angular-google-chart/angular-google-chart#295]
I am using the google-chart directive to draw Bar chart, Pie Chart and Tables in my HTML.
The HTML contains all the data that is required by these Charts.
Just received a weird requirement from client that the html should work in a disconnected environment with no internet access. Is there a way to make this work in such an environment?
What are the files that I would need to bundle with the HTML for this to work.
Currently I just include the following script files in my html
<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-google-chart/0.1.0/ng-google-chart.js" type="text/javascript"></script>

A Quick answer will be greatly appreciated.

**Comment by nbering** [comment]
How disconnected are you talking? If you've already fetched the API and are just continuing to display the data it will work as long as your data is pre-loaded and you are just drawing charts. If you're talking about something like a hybrid mobile app and you need to use Google Charts completely offline, that is not supported. It is unfortunately against the Google Charts Terms of Service to store or cache the library by any other mechanism than they may provide with their api loader.

**Comment by achoudhurys** [comment]
Thanks for the reply.
Disconnected means a complete lockdown, the box will have no network connection.
Understood that due to Google Chart policy it will not work. 
Assuming that we can provide a very limited access based on URL then access to following url's should make this work correct?
www.google.com for jsapi
ajax.googleapis.com for angular
cdnjs.cloudflare.com for ng-google-chart.js

When I fire up Fiddler and reload the page(after clearing the cache and all history)
I see only the following downloads happening

https://ajax.googleapis.com/ajax/static/modules/gviz/1.0/core/tooltip.css

http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js

https://cdnjs.cloudflare.com/ajax/libs/angular-google-chart/0.1.0/ng-google-chart.js

https://www.google.com/uds/api/visualization/1.0/1195ca6324d5ce101c2f520f3c62c843/format+en,default+en,ui+en,corechart+en.I.js

https://www.google.com/uds/api/visualization/1.0/1195ca6324d5ce101c2f520f3c62c843/ui+en.css

https://www.google.com/uds/?file=visualization&v=1&packages=corechart&async=2

https://www.google.com/jsapi

**Comment by nbering** [comment]
You'll need to check with the Google team for URL specifications, but I think the actual URLs that load would depend on the packages you select, and also the version of the API (they update it every once in a while). Also, be aware that while this library has not migrated, the loader endpoint specified by google has change from https://www.google.com/jsapi to https://www.gstatic.com/charts/loader.js and I imagine that would affect a lot of the other package URLs that their loader handles.

If you have time to switch over though, I would recommend just changing to something like D3.js so you won't have the Terms of Service to deal with and can just serve the JS locally.

**Comment by achoudhurys** [comment]
I like angular-google-chart that you provided. Doesn't require me to write all the javacode, just provide the data which I can inject during runtime. Thanks for your input. Also thanks for directing me to D3.js. It looks promising
