### ISSUE TITLE
Chart does not render inside Material mdTabs

### ISSUE THREAD

**Issue by Joystan** [angular-google-chart/angular-google-chart#297]
Hello!

I am using Google chart inside [Angular Material tabs](https://material.angularjs.org/latest/api/directive/mdTabs). 

The chart renders fine for the first time when you load the page, but when you change pages and come back to this page it gives a container error and the charts don't load. 

Is anyone aware any fix for this?

**Comment by nbering** [comment]
Please provide a live code example. I can help debug this, but I I don't have the time at the moment to try to reproduce the error from your description.

If you can't reproduce in a jsFiddle or codepen, at least provide any javascript console errors and/or a screenshot/screen recording of the issue.

**Comment by Joystan** [comment]
@nbering Thanks for your response. The problem was not with angular-google-charts it was with mdtabs which is resolved. 

Thank you again.

**Comment by nbering** [comment]
No problem. Glad you got it sorted out. 😄
