### ISSUE TITLE
How to add annotation label in bar chart

### ISSUE THREAD

**Issue by samimaliks** [angular-google-chart/angular-google-chart#301]
I am unable to add annotation chart in bar.When I add a role:annotation, chart disappear.

**Comment by nbering** [comment]
If this is with the Material Bar charts, I imagine they haven't implemented that, yet. Doesn't sound something something from Angular Google Chart, though.

Apologies, I didn't realize I had missed your issue. Closing as upstream, you're welcome to check the issues on https://github.com/google/google-visualization-issues for google's own issue tracker.
