### ISSUE TITLE
Percent format in hover values in bars

### ISSUE THREAD

**Issue by xzegga** [angular-google-chart/angular-google-chart#303]
I am formating vAxis labels in percentaje and work well, the problem is with values on hover for each bar, these is still in decimals and not format in percents

```
 options: {
  vAxis: {
	title: 'V Axis',
	format: 'percent'
  },
  hAxis: {
	title: 'X Axis Values',
	format: ''dd/MM/yyyy''
  }
},
```

![clipboard01](https://cloud.githubusercontent.com/assets/4492277/22666927/3959f46e-ec80-11e6-8a0d-eb82991cd83f.jpg)

How I can format the hover values in percent too?

**Comment by nbering** [comment]
Yes, that use case is covered.

Docs:
http://angular-google-chart.github.io/angular-google-chart/docs/0.1.0/guides/how-to-formatters/

Example using formatters (switch to table chart type for formatters example):
http://angular-google-chart.github.io/angular-google-chart/docs/latest/examples/multi-chart/

**Comment by nbering** [comment]
I'm going to presume this is solved since there's hasn't been any activity in months.
