### ISSUE TITLE
Library settings - mapsApiKey is not read/applied

### ISSUE THREAD

**Issue by aidaeology** [angular-google-chart/angular-google-chart#305]
When using the GeoChart I hit an API rate limit for maps - see error:

> You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_  For more information on authentication and Google Maps Javascript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key

I created a Google Maps API Key and updated the settings for google.load() as specified in https://developers.google.com/chart/interactive/docs/basic_load_libs  as such:
```
      google.load(
        'visualization', '1',
        { 
          packages: ['corechart', 'calendar', 'geochart'],
          mapsApiKey: 'xxxYYzzzzzZZZZ',
          language: 'en_US'
      });
```
Still getting same error, it appears the mapsApiKey settings is not being read or applied on chart init.

**Comment by nbering** [comment]
May require update to new loader. Will look into this. May take a couple of days for a resolution just because of my work schedule though.

**Comment by aidaeology** [comment]
Hi Nic! is there an update on this?

**Comment by nbering** [comment]
Sorry, I've had a busy month at work and never got around to this. Things are slowing down a bit, I might be able to fit something in this week.

**Comment by nbering** [comment]
PR #310 solves this issue. I tested it myself with my maps API key. The new documentation will also include an example of this. Official 1.0.0-beta.1 release coming soon. Doing away with some internal code related to loading and hopefully fixing up tests a bit.
