### ISSUE TITLE
sparkline gvjs_1aa is not defined

### ISSUE THREAD

**Issue by 1mike12** [angular-google-chart/angular-google-chart#307]
I know this is not really a supported product on google's end but wondering if anyone has any idea what the error means. Google doesn't turn up a single result. 

`gvjs_1aa is not defined×`

This plunker was made in 2013 https://github.com/angular-google-chart/angular-google-chart/issues/21 that apparently used to work http://plnkr.co/edit/XAdmUC?p=preview

**Comment by nbering** [comment]
That sample is using v0.0.5, which was 6 versions behind even before I did a major rewrite of much of the library. I'm afraid I can't support that version. If you can demonstrate the issue on a more recent version I may look at it.

The current version is v0.1.0.

**Comment by nbering** [comment]
Looking into this a little deeper... is this using Image Charts through chartwrapper? I didn't even know Google supported that. But either way, ImageCharts were deprecated in 2012. It wouldn't surprised me if they turned off support for that feature at any time.

**Comment by 1mike12** [comment]
yeah, I personally am using 0.1.0, but sparkline itself still works. They have a fiddle from the official docs https://jsfiddle.net/api/post/library/pure/

But last night I tried to just use raw google charts, and create a custom angular component. I did this by including the script `<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>`, but when I did, it caused the regular angular-google charts to break. Any suggestions?

**Comment by nbering** [comment]
Don't call load in your own code. If Angular-Google-Chart sees that there is an on load callback already set, it will save that itself and call your callback when it receives the callback. There can only be on on load callback, and you can only call load once.

I might look at checking to see if the library is already loaded, but the google loader doesn't present much of an API for checking whether the library is loaded and what packages are loaded.

**Comment by nbering** [comment]
If you need to use the gstatic endpoint, #310 added this capability on the development branch. Planning to release 1.0.0-beta.1 very soon. Just cleaning up issues to see if anything else is needed for the 1.0 release.
