### ISSUE TITLE
Tries to open file://www.google.com/jsapi from electron

### ISSUE THREAD

**Issue by KromDaniel** [angular-google-chart/angular-google-chart#314]
Hey
I'm using electron v1.4.8 and have the next issue:

Getting error when it tries to load content from `file://www.google.com/jsapi` I guess it's because electron URL begins with `file` and not with `http\s`.

When I use google charts without this module
`<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>`
it works (but not comfortable with angular)

Thanks!

**Comment by nbering** [comment]
What version of angular-google-chart?

**Comment by KromDaniel** [comment]
`<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-google-chart/1.0.0-beta.1/ng-google-chart.min.js" type="text/javascript"></script>`

**Comment by nbering** [comment]
Ok. I'll fix this in beta-2. Probably out this weekend. I figured I was safe to use protocol relative. I should have known better... this would break cordova, too. Thanks for testing the beta version.

**Comment by nbering** [comment]
I should add, you can switch to gstatic and you should be ok. I believe I hard-coded https for the gstatic loader. There are instructions in the docs under [agcGstaticLoaderProvider](http://angular-google-chart.github.io/angular-google-chart/docs/latest/providers/agcGstaticLoaderProvider/).
