### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by devfxplayer** [angular-google-chart/angular-google-chart#315]
Cannot read property '0' of undefined

![image](https://cloud.githubusercontent.com/assets/10968342/25771704/6b92748e-3261-11e7-8355-34f2415fc590.png)

**Comment by nbering** [comment]
Need more information. Can you show me the error from the console? That should have a file and line number, but it looks like something is expecting an array and getting undefined. This may not be an angular-google-chart's code.

It would also be helpful to know the type of chart you're using, and the version of angular-google-chart.

**Comment by devfxplayer** [comment]
I use Bar Chart Example and does have anything in the console.
Using the Line chart works!

**Comment by nbering** [comment]
@devfxplayer Is this still a problem for you? I need more information to help if it is.

- Which browser?
- What settings (if not the default) are you using for the api configuration?
- Which version of the bar chart example? The documentation shows all released versions between 0.0.11 and 1.0.0-beta.1.
- I also need to see some code if this is an example copied from anywhere but http://angular-google-chart.github.io/angular-google-chart/.

I've tested the current version of the [Bar Chart example](http://angular-google-chart.github.io/angular-google-chart/docs/1.0.0-beta.1/examples/bar/) on latest Chrome, Firefox, and Safari with the latest macOS release with no issues.

**Comment by devfxplayer** [comment]
Thanks is working now! you can close this if you like.

**Comment by jsteffensen** [comment]
For future drop-bys - I had this error because I used the Barchart example `$scope.myChartObject.data` but had forgotten to include the preceeding `$scope.onions` that the `$scope.myChartObject.data` refers to ...
