### ISSUE TITLE
Javascript file wont download from 'https://www.google.com/jsapi' as it violates the following Content Security Policy

### ISSUE THREAD

**Issue by DevankAgarwal** [angular-google-chart/angular-google-chart#316]
![a](https://cloud.githubusercontent.com/assets/9546432/26672607/60dab3d2-46d7-11e7-89d1-02b061252766.jpg)

On my server the Content Security Policy is strict, which does not allow any javascript file to be downloaded from www.google.com. As enabling whole google domain is very risky. max i can do is to allow and subdomain of google.

Please suggest me any alternative for getting the file.

**Comment by nbering** [comment]
See [agcGstaticLoaderProvider](http://angular-google-chart.github.io/angular-google-chart/docs/1.0.0-beta.1/providers/agcGstaticLoaderProvider/) in the 1.0.0-beta.1 release. It uses the www.gstatic.com endpoint to get the loader.

More releases to come as people provide feedback, I may switch default loader provider to gstatic before the 1.0.0 release.

See [Load the libraries](https://developers.google.com/chart/interactive/docs/basic_load_libs) from Google's documentation to see where this upstream requirement comes from. Ultimately, there's plenty that will break when you turn on CSP. I personally still encourage it's use, where appropriate, but I can't control the upstream charts library.

You may still encounter issues for CSP while using google charts, a quick search on the upstream issues repository returned google/google-visualization-issues#1356, google/google-visualization-issues#2131, and a loosely-related google/google-visualization-issues#2166.

**Comment by nbering** [comment]
Closing as not actionable. At best I could provide some documentation about using CSP with Google Charts, but that would be prone to breaking as I have no control or visibility into what google writes into their library. If you want to submit that documentation as a pull request, I may accept it, though. 

I also have no control over what CSP rules people write. Adding the Content Security Policy header is a really easy way to break anything on your site, and is not specific to this wrapper library. You're welcome to let me know if there's something that is within my power to change that would help.

**Comment by DevankAgarwal** [comment]
Thanks a lot for the details.
Somehow it worked for me by changing the CSP rules to only allow https://www.google.com/jsapi rather https://www.google.com
