### ISSUE TITLE
chart , selectedItem , chartwrapper locals on select event when console.logged appear in weird naming convention So I am not able to decide which methods I can use on them.

### ISSUE THREAD

**Issue by SaiKrishnam** [angular-google-chart/angular-google-chart#317]

**Comment by SaiKrishnam** [comment]
![image](https://cloud.githubusercontent.com/assets/9619747/26735330/1936c8b2-4787-11e7-9998-3ef5d1ea7376.png)

**Comment by nbering** [comment]
I'm sorry, I'd like to help you, but your question is very poorly formatted, and your screenshot tells me very little about what your are console.logging. Can you show me the code that produced that output?

The upstream google charts library is minified and obfuscated. Only properties and methods on the public API have meaningful names. See https://developers.google.com/chart for reference material. Do not reference anything that appears obfuscated, as it will likely break when Google does a new release.

**Comment by SaiKrishnam** [comment]
` <div google-chart chart="$chCtrl.chartData"
                     agc-on-select="$chCtrl.onChartItemSelected1(chart,selectedItem,chartWrapper)"
</div>`

look at agc-on-select , capturing it in my javascript file,
 self.onChartItemSelected1 = function (c,si,cw) {
            console.log(c);
            console.log(si);
            console.log(cw);

        }
The screen shot shows my console log.
![image](https://cloud.githubusercontent.com/assets/9619747/26736826/44a49f5a-478d-11e7-8be4-83d6875fb5a3.png)

**Comment by SaiKrishnam** [comment]
Sorry for my poor formatting, please let me know if I am still not clear.

**Comment by nbering** [comment]
In your javascript, `c` is the chart instance for whatever type of chart you have. To learn what methods you can used to interact with that option, check the documentation for the specific chart type you are using on https://developers.google.com/chart.

`si` is an object that represents the row/column in the dataTable that was selected. If a legend item was selected, the row will be null, and the column will have a value. These row/column references match up to the rows in columns in your DataTable.

`cw` is an instance of google.visualization.ChartWrapper. See https://developers.google.com/chart/interactive/docs/reference#chartwrapperobject.

**Comment by SaiKrishnam** [comment]
thank you.

**Comment by nbering** [comment]
You're welcome. Best of luck.
