### ISSUE TITLE
How to disable or remove label from column chart?

### ISSUE THREAD

**Issue by corientdev** [angular-google-chart/angular-google-chart#318]
How to disable or remove label from column chart?

**Comment by nbering** [comment]
Which label? Can you share a screenshot with the label you want to remove highlighted?

**Comment by nbering** [comment]
I'm trying to keep the open issues to a minimum as open issues increase administrative overheard whenever I want to triage which issues to work on while I have time to donate to the project. I will re-open this issue if more information provided.
