### ISSUE TITLE
Google chart geomap highlight region

### ISSUE THREAD

**Issue by akvaliya** [angular-google-chart/angular-google-chart#322]
I have used below options.
`geo = {
            type: 'GeoChart',
            options: {
                width: '100%',
                height: 300,
                chartArea: { left: 10, top: 10, bottom: 0, height: "100%" },
                colorAxis: { colors: ['#aec7e8', '#1f77b4'] },
                displayMode: 'regions',
                resolution : 'provinces'
            }
}`

![](https://i.stack.imgur.com/JSYY4.png)

Above is the chart i have displayed. when i mouse hover on region i see pointer on footer bar which displays 1-7.

Is there any way to highlight regions when mouse hover on footer bar?

**Comment by nbering** [comment]
@akvaliya Referring to the upsteam documentation at https://developers.google.com/chart/interactive/docs/gallery/geochart, I don't see any such option. So unless there's something undocumented I would have to say, "No this is not possible." I'm not very familiar with GeoCharts though, so if you'd like to pursue this question further, I can direct you to the [upstream support channels](https://developers.google.com/chart/interactive/support) where you might have better luck.
