### ISSUE TITLE
Chart Editor

### ISSUE THREAD

**Issue by drGarbinsky** [angular-google-chart/angular-google-chart#327]
Looking for some help getting the chart editor to work. Is this directly supported by this project? Any tips would be appreciated.

**Comment by nbering** [comment]
You can enable it from the chart options, but I've never tested it, and from what I've read in the docs there's not much I can do to add hooks to support it as Google hasn't provided much of an API for this feature. If your data changes, the chart will redraw and destroy the Editor's current state. There doesn't seem to be much I can do about that except to possibly add a bind-once type feature.

**Comment by drGarbinsky** [comment]
can you give me a quick example of how to enable it in the options. Just a one liner would that shows the option name and what not.  If this is something I need would you be open to a PR at some point?

**Comment by nbering** [comment]
I'll get back to you when I'm off the clock, and provide a CodePen example or something.

**Comment by drGarbinsky** [comment]
Much appreciated.

**Comment by nbering** [comment]
I played around with this, and I'm going to have to call it unsupported. I really just could not get it to work.

It's also one of those features that just doesn't make a lot of sense to use with this library. The Chart Editor is about adding dynamic features to Google Charts, which is exactly what AngularJS is bringing to the table. Trying to use them together just never ends well.

I could go on, but basically the Google Charts library is built to be very encapsulated, to the point that the API is very restrictive. You end up with situations where you just can't do what you need to do to make your AngularJS feature work with their Google Charts feature.

**Comment by drGarbinsky** [comment]
Got it. Thanks for the effort!
