### ISSUE TITLE
Organization chart

### ISSUE THREAD

**Issue by Bhee** [angular-google-chart/angular-google-chart#329]
Is this directive module support Organization Chart?

**Comment by nbering** [comment]
Yes. I don't have an example, but the chart type is supported. Use the type `OrgChart`, and follow the data structures and options from the [OrgChart Documentation](https://developers.google.com/chart/interactive/docs/gallery/orgchart).

**Comment by Bhee** [comment]
Thank you @nbering 

As you mentioned I used  below code to set data to the chart but getting error:
**You called the draw() method with the wrong type of data rather than a DataTable or DataView×**

```
$scope.myChartObject.type ="OrgChart";
$scope.myChartObject.data =  {
    "cols": [ 
      {
        "id": "month",
        "label": "Month",
        "type": "string"
      },
       {
        "id": "parentid",
        "label": "Parent",
        "type": "string"
      }
      
    ],
    "rows": [
      {
        "c": [
          { "v": "Jan"  },
           { "v": "" }      /*no parent*/
        ]
      },
      {
        "c": [
          {   "v": "Feb"   },
          {   "v": "Jan"  }
             ]
      },
        {
        "c": [
          {  "v": "March"  },
          {  "v": "Jan"    }
        ]
      },
      {
        "c": [
          { "v": "April" },
          {  "v": "March"  }
        ]
      },
      {
        "c": [
       {v": "May"  },
        {  "v": "Feb"}
        ]
      },
       {
        "c": [
          {"v": "June"   },
          {  "v": "jan"    }
        ]
      }
    ]
  };
```
Any help on this would be appreciated.
Thanks

**Comment by nbering** [comment]
Using my CodePen template as a base, and your data structure from above (after resolving some syntax errors), I came up with [this working sample](https://codepen.io/nbering/pen/GQdwqW?#).

**Comment by Bhee** [comment]
Thank You.
