### ISSUE TITLE
Calendar chart - legend showing as NaN

### ISSUE THREAD

**Issue by rafbel** [angular-google-chart/angular-google-chart#331]
I'm having trouble using the calendar chart. Whenever I insert data, the legend shows as NaN - NaN. 

![image](https://user-images.githubusercontent.com/14187686/36750869-5f46b4fe-1bdd-11e8-8548-3fe14acff2e3.png)

However, when there is no data it shows as 0 - inifinity.

My data is insert like this: 

![image](https://user-images.githubusercontent.com/14187686/36750948-8c2ea35a-1bdd-11e8-9fe8-3ab8ad1512e8.png)

Where reportsConverted is basically: 

![image](https://user-images.githubusercontent.com/14187686/36750991-aa4f429a-1bdd-11e8-9b11-8d67a4f0e455.png)

Any idea what it could be? If for all dates, the value is 0, I believe the legend should show as 0 - 0 or something of the sort at least.

**Comment by nbering** [comment]
Can you give me a live sample, like a JSFiddle or CodePen? I don't have enough information from your screenshots to replicate the issue.

**Comment by rafbel** [comment]
Problem is fixed if I set a max and min value for the axis.

**Comment by nbering** [comment]
I'm glad you managed to work it out, sorry I couldn't have been of more assistance.

**Comment by rafbel** [comment]
You were great! Thanks for replying and trying to help!
