### ISSUE TITLE
trigger draw() manually

### ISSUE THREAD

**Issue by gcubar** [angular-google-chart/angular-google-chart#332]
Hi collegue,

Is there any way to dispatch manually draw() method of google visualization API through the angular directive? 
I am trying to apply some custom animations after chart are ready, but chart are rendered many times. In some cases onChartReady event are triggered two times and in another cases three times. Its unpredictable! 
Then when we receive the first onChartReady event, we begin animation, but at a middle of animation process, we receive another onChartReady event and the chart are rendered again losting the animation sequence.
 
I know I update 'chart' attribute value many times, and after each updates its trigger the draw() method, then it makes happen my issue, but how i can fix this or use some workaround to solve my issue?

Currently I am using 0.1.0 version of angular google chart, because we have many old chart and i don't know if updates to the currently 1.0.0 beta version affects that charts.

Many thanks.

**Comment by nbering** [comment]
Hi @gcubar. There's no functionality built-in to provide a hook to call `draw()` yourself, but without knowing the specifics of what you are trying to animate or how, there's a couple of tips I could give.

One is that `agc-on-ready` hooks into the `onChartReady` event, as you've indicated. One of the possible causes of unpredictability is that the `onChartReady` event is called by the underlying API whenever the chart wrapper is ready to handle input. This occurs both when the chart is instantiated, and after every call to draw.

One thing you should avoid when using the on-ready event, is changing anything that would cause another digest cycle iteration in Angular. To get the data-binding to work, the directive watches a subset of the ChartObject fields. That's implemented here:
https://github.com/angular-google-chart/angular-google-chart/blob/cdcba1e7eab1dde3df66df283142faba92ab80fc/src/GoogleChartController.js#L86-L91

So don't change any of these things if you don't want to trigger another draw.

If you want to trigger your logic only when the chart is going to draw, and not when the chart is settling in to be ready for input, use [agc-before-draw](http://angular-google-chart.github.io/angular-google-chart/docs/0.1.0/directives/agcBeforeDraw/) behavioural directive. Sorry, it's not well documented, but works pretty much the same as `on-ready`, except that it triggers on and angular-library-level event, just before calling `draw()`. The same caveat as above applies... to avoid triggering another draw, do not change any of the watched properties.

**Comment by nbering** [comment]
Oh.. I almost forgot to give the second tip.

The second option is to capture the chart object in the on-ready handler, and call draw yourself. Unfortunately, this will not block the directive from calling draw on you when you're not expecting it. There's really not a lot that can be done in that regard without some modification. Handling draw intelligently is most of what this directive does for Angular users, but the way it's implemented works for the 98% of cases, but not great for very custom cases. If it's really problematic, I might suggest looked back at the earlier versions of the directive and seeing what it actually does. The core functionality is probably less than 250 lines and you could write your own directive to do the same.

**Comment by nbering** [comment]
No response. Closing as aged. If you still have issues, I can re-open the request.
