### ISSUE TITLE
Creating charts with a ng-repeat

### ISSUE THREAD

**Issue by tinba12** [angular-google-chart/angular-google-chart#334]
I want to have multiple charts based on a variable. I have
 `<div class="chat" google-chart chart="chartoptions.chartData" style="height:600px; width:100%;" ng-repeat="chartoptions in totals" ></div>`
It creates the proper number of charts but they all use the chartData from the last element.

**Comment by nbering** [comment]
I'd need a complete working sample to debug your issue. Can you reproduce the issue on CodePen, JSFiddle or Plunker so I can see what's going on? My first guess is that you're working with something by reference in your controller code and re-writing your own data, but I can't tell without a complete sample.

I use [this pen](https://codepen.io/nbering/pen/pwWjyW) as a starting point, usually.

**Comment by tinba12** [comment]
Using your example I figured out what was wrong. I did not use angular.copy. Thanks for the help.

**Comment by nbering** [comment]
@tinba12 Excellent! I'm glad you figured it out.
