### ISSUE TITLE
Loading error trying to add angular-google-chart to my project.

### ISSUE THREAD

**Issue by scottcarter87** [angular-google-chart/angular-google-chart#338]
I have installed per the instructions and when I load my page I get the following error.

<img width="1920" alt="screen shot 2018-08-08 at 8 28 05 am" src="https://user-images.githubusercontent.com/7588413/43836972-0b861f9e-9ae5-11e8-99b5-3193c7968c39.png">

Somebody please help!  I cannot figure this out!  I am using version 1.0.0-beta.1 and AngularJS 1.5.8

**Comment by scottcarter87** [comment]
Downgraded to 0.1.0 and now everything works fine.

**Comment by nbering** [comment]
@scottcarter87 Did you install from NPM? A prior issue pointed out that there was an issue with the version I pushed to NPM, but that wasn't present in the CDN release.

**Comment by nbering** [comment]
In #336, we learned that the minified file on NPM, for v1.0.0-beta.1 does not match the version published to https://cdnjs.com/. That was probably my fault - I may have just done some release steps out of order.

I'm going to close this for now - if you're still having issues, I'd be happy to re-open the issue.
