### ISSUE TITLE
Issue in TypeScript Angular Google Chart : GeoChart: getSelection()

### ISSUE THREAD

**Issue by manurag02** [angular-google-chart/angular-google-chart#340]
I am using Angular-google-chart in my project and when I am trying to get the name of the clicked country I get the following errors : Invalid column index null. Should be an integer in the range [0-1] errors.ts:35 ERROR Error: Not an array

stack blitz link :- https://stackblitz.com/edit/angular-advanced?embed=1&file=src/app/single-country/single-country.component.ts&hideExplorer=1&hideNavigation=1

I am very close to complete my project but this is holding it.

**Comment by nbering** [comment]
I'm not really sure how to help you from the link you're provided. I don't see any attempt to use that method call.

Can you reduce an example to just what you're trying to do that fails?

**Comment by manurag02** [comment]
I accidentally edited the module as i had to deliver the project. My bad. Closing the INC.
