### ISSUE TITLE
GMT Date on Explorer 

### ISSUE THREAD

**Issue by ammarax** [angular-google-chart/angular-google-chart#341]
if you use a Date object on Explorer (7,8, Edge) it will broke the algorithm to collegue 2 point 
one in summer time the other in standard time, and loop to infinite

an example of JSON that make this error
{"rows":[{"c":[{"v":"Date(2018, 2, 25, 0, 1, 53)"},{"v":"0"}]},{"c":[{"v":"Date(2018, 2, 25, 4, 28, 57)"},{"v":"0"}]}]}

tested on 
angular google chart v 0.1.0 
angular 1.2.4

**Comment by nbering** [comment]
Angular-google-chart doesn't do anything to the DataTable inputs. You'll want to check for an upstream issue in [google/google-visualization-issues](https://github.com/google/google-visualization-issues). If you can actually pin it to an issue in this library, I'm happy to re-open and help out, but I don't see any connection to the wrapper code.
