### ISSUE TITLE
responsive chart

### ISSUE THREAD

**Issue by alirezaseif28** [angular-google-chart/angular-google-chart#343]
Hi.
I drawing chart with angular-google-chart.
it is good.
then chart fullscreen look like below
`var elem = document.getElementById("myvideo");
function openFullscreen() {
  if (elem.requestFullscreen) {
    elem.requestFullscreen();
  } else if (elem.mozRequestFullScreen) { /* Firefox */
    elem.mozRequestFullScreen();
  } else if (elem.webkitRequestFullscreen) { /* Chrome, Safari & Opera */
    elem.webkitRequestFullscreen();
  } else if (elem.msRequestFullscreen) { /* IE/Edge */
    elem.msRequestFullscreen();
  }
}`
and then not responsive in full screen.
please help me.

**Comment by nbering** [comment]
Module sets up a handler to listen for window resize events, which emits `resizeMsg`:
https://github.com/angular-google-chart/angular-google-chart/blob/cdcba1e7eab1dde3df66df283142faba92ab80fc/src/googlechart.module.js#L9-L11

And then registers to listen for that, and then triggers a re-draw of each chart instance:
https://github.com/angular-google-chart/angular-google-chart/blob/cdcba1e7eab1dde3df66df283142faba92ab80fc/src/GoogleChartController.js#L59

If it's not triggering a resize event when it goes fullscreen... you could use the promise returned by [Element.requestFullscreen()](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen) and emit `resizeMsg` from the root scope to re-draw all the charts. I'm surprised it's not emitting the resize event already, though.

**Comment by alirezaseif28** [comment]
thanks a lot.
I trace code and see call emit resizeMsg.
but width fullscreen and not height responsive below image.
[image](https://play.minio.io:9000/alirezaseif/1.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20200226%2F%2Fs3%2Faws4_request&X-Amz-Date=20200226T144403Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=56e64b0fc215be0c1697a264ec59401caf598cadd3ffd37543e1ada346f377ca)
best regards

**Comment by nbering** [comment]
That looks like you probably just need to set the height property on the chart options.

https://developers.google.com/chart/interactive/docs/gallery/linechart#configuration-options

**Comment by alirezaseif28** [comment]
thanks a lot.
I want width and height responsive.
please help me.

**Comment by nbering** [comment]
The chart builds to the size you specify, or tries to fill the container.

You'll probably need some CSS to make the container element height-responsive. But how to do that is beyond the scope of this project.

Here's an example where I was working with something else (positioning image elements relative to the chart axes), but it's the only sample I have ready where I override the height of the chart in CSS.

https://codepen.io/nbering/pen/yNZxKr

Don't pay any attention to this part:
```css
#container_div {
  position: relative;
}
```
It was needed for rendering the weather icons which is not what you're working on.

**Comment by alirezaseif28** [comment]
thanks a lot.
