### ISSUE TITLE
Chart not loading

### ISSUE THREAD

**Issue by pkparadigm** [angular-google-chart/angular-google-chart#348]
We use the angular-google-chart. It was working for us till very recently. But it stopped working all of a sudden. I see a 404 error in our logs. This happens when js is trying to reach the google servers - 

https://www.google.com/uds/?file=visualization&v=1&packages=corechart&async=2

The above link gives a 404 and then the chart stops loading. 

thanks

**Comment by nbering** [comment]
That's not a URL called by this library, directly. Probably an upstream issue. Historically, it's been pretty common to see weird caching issues and stuff when the Google Charts team releases a new version. It could be temporary.

Try checking out https://github.com/google/google-visualization-issues/issues.
