### ISSUE TITLE
Please add support for the Google Chart Toolbar

### ISSUE THREAD

**Issue by jasonadt** [angular-google-chart/angular-google-chart#47]
**Please add support for the Google Chart Toolbar**

I love this angular module, however I wish that it had built-in support for Google's Chart Toolbar (for exporting, etc.). 

For more info: https://developers.google.com/chart/interactive/docs/gallery/toolbar?hl=en

**Comment by nbering** [comment]
At one point, I thought this might be reasonable. I'm going to remove this from the roadmap for now. It just takes too much effort for what it provides.
