### ISSUE TITLE
Integrating with ControlWrapper

### ISSUE THREAD

**Issue by alpine00** [angular-google-chart/angular-google-chart#54]
I would like to help with enhancing the functionality by adding support for ControlWrapper( https://code.google.com/apis/ajax/playground/?type=visualization#chartrangefilter_control ). Any hints or support on this side, would be very helpful. Since I am fairly new to Angular, a wiki of the whole directive would be very helpful.
Regards,

**Comment by jose-goncabel** [comment]
Hello, something new about this issue? I would really appreciate this functionality implemented. I would be happy to contribute but feel as if everything is too complex to bring something of value.
Thanks a lot.

**Comment by Balrog30** [comment]
This is something I really wanted to do at one point, but lots a lot of steam to get it done. It's pretty complicated for what you get out of it in the end. It would probably be easier to integrate into a specific app than build this feature as a general-purpose library.

**Comment by jose-goncabel** [comment]
Ok, I understand it. I will try to do it that way. Many thanks.

**Comment by nbering** [comment]
As mentioned, this is more complicated than it's worth for the moment. I'm pruning issues to be more manageable, and I think this is going to get trimmed from the roadmap for now. Maybe one day, but no plans for now.
