### ISSUE TITLE
Documentation for retrieving `chartWrapper` in `onReady` function

### ISSUE THREAD

**Issue by mikberg** [angular-google-chart/angular-google-chart#55]
Through some digging in the source code, I found out that it's possible to pass a variable named `chartWrapper` to a function given in the `onReady` attribute on the directive. This is very useful, e.g. for attaching event listeners:

    $scope.chartReady = function(chartWrapper) {
        $window.google.visualization.events.addListener(chartWrapper, 'select', function() {
            console.log('select event fired!');
        });
    };

It's a good feature, but it's not documented. In the sample, the `onReady` function passed in is not utilizing this feature.

**Comment by ArtCraft** [comment]
thank you for pointing on existance of this feature
