### ISSUE TITLE
PNG Retrieval

### ISSUE THREAD

**Issue by dwillie** [angular-google-chart/angular-google-chart#62]
https://developers.google.com/chart/interactive/docs/printing

Can't seem to recreate this. I retrieve my element (using document.getEleme...) and pass it through to the google.visualization.LineChart function, but I simply receive an "undefined is not a function" TypeError. LineChart() is defined, and my element is defined, so I'm not sure how to proceed from here. Is my approach correct in the context of your library?

Thanks

**Comment by LuqmanParavetty** [comment]
Hi,

I am not getting fetched data "on ready" of google-chart while i followed above code nbering  described. Can anyone please help me on this?

**Comment by nbering** [comment]
The API changed to agc-on-ready to resolve conflicts with ui-bootstrap when I converted the behavioral properties to directives.

**Comment by LuqmanParavetty** [comment]
AWESOME!!... thank you so much updating rapidly...

**Comment by akshay-bbytes** [comment]
var chartObject = chartWrapper.getChart();
var imageURL =  chartObject.getImageURI();

Is getImageURI function work for gauge type chart
Below is the code for chart object:

 var countObject = {};
                countObject .type = "Gauge";
                   $scope.countObject .data = [
                        ['Label', 'Value'],
                        ['Total', 80]
                    ];
                    countObject .options = {
                        width: 300,
                        height: 250,
                        minorTicks: 10,
                        max:100000,
                        chartArea: {left: 50, top: 30, bottom: 10, right:200, height: "100%", width: "100%"}
                    };

Can anyone please help me on this asap?

**Comment by nbering** [comment]
Not supported on gauge chart. See https://developers.google.com/chart/interactive/docs/gallery/gauge#methods for supported methods.

**Comment by akshay-bbytes** [comment]
Okay Thanks.

**Comment by lkptl1** [comment]
but animation is not working with agc-on-ready
