### ISSUE TITLE
Cannot get custom tooltip to work on scatter chart with multiple series

### ISSUE THREAD

**Issue by r0ughnex** [angular-google-chart/angular-google-chart#74]
The Json format of data I feed to the scatter chart is show below.
![chart_data](https://cloud.githubusercontent.com/assets/7619803/3007231/76aad966-de76-11e3-9d72-cb111187a93a.png)

I use the last column for the tooltip, but the custom tooltip only pops up on the
last series of values, the other values on the graph still seems to render the default
tooltip with x,y. ( check images below )
![chart_1](https://cloud.githubusercontent.com/assets/7619803/3007235/b2cf7776-de76-11e3-8abc-86fb4094bcc9.png)
![chart_2](https://cloud.githubusercontent.com/assets/7619803/3007236/b3b731ba-de76-11e3-94ab-61377116f3d0.png)
![chart_3](https://cloud.githubusercontent.com/assets/7619803/3007237/b4d627c2-de76-11e3-88a8-3640b44caaba.png)

Any idea how to get the custom tooltip to popup on all the values rendered in the graph?

**Comment by nbering** [comment]
Closing as aged. Hope you found your answer at some point.
