### ISSUE TITLE
note: table chart example doesn't work with firebug

### ISSUE THREAD

**Issue by developitz** [angular-google-chart/angular-google-chart#80]
We just spent some time trying to get the table-chart example running. It doesn't work with Firefox 30.0 beta and Firebug 2.0b8. Turning Firebug off or using another browser solves the problem. The error message was 'Hv is undefined'. The other examples work.

Other bug in table-example:
$scope.chart.options.tooltip is undefined
$scope.chartSelectionChange@http://bouil.github.io/angular-google-chart/partials/fat.js:140:13

**Comment by Balrog30** [comment]
I think this issue has aged away. In retrospect, it was probably something on the google end of things since the naming looked minified and we weren't minifying until recently.  Probably something to do with using TableChart in ChartWrapper.
